/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdministratorRouteImport } from './routes/_administrator'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMyProfileRouteImport } from './routes/settings/my-profile'
import { Route as SettingsLoginAndSecurityRouteImport } from './routes/settings/login-and-security'
import { Route as SettingsLanguageAndRegionRouteImport } from './routes/settings/language-and-region'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as WorkspaceTaskSummaryRouteImport } from './routes/_workspace/task-summary'
import { Route as WorkspaceScheduleRouteImport } from './routes/_workspace/schedule'
import { Route as WorkspaceProjectCenterRouteImport } from './routes/_workspace/project-center'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace/profile'
import { Route as WorkspaceOverviewRouteImport } from './routes/_workspace/overview'
import { Route as PublicHelpCenterRouteImport } from './routes/_public/help-center'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdministratorFinancialRouteImport } from './routes/_administrator/financial'
import { Route as CommunitiesCodeIndexRouteImport } from './routes/communities/$code/index'
import { Route as WorkspaceProjectCenterIndexRouteImport } from './routes/_workspace/project-center/index'
import { Route as WorkspaceJobsIndexRouteImport } from './routes/_workspace/jobs/index'
import { Route as WorkspaceWorkbenchIndexRouteImport } from './routes/_workspace/_workbench/index'
import { Route as AdministratorAdminIndexRouteImport } from './routes/_administrator/admin/index'
import { Route as WorkspaceProjectCenterTabRouteImport } from './routes/_workspace/project-center/$tab'
import { Route as WorkspaceJobsNoRouteImport } from './routes/_workspace/jobs/$no'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth/reset-password'
import { Route as AdministratorFinancialSettingRouteImport } from './routes/_administrator/financial/setting'
import { Route as AdministratorFinancialReimbursementsRouteImport } from './routes/_administrator/financial/reimbursements'
import { Route as AdministratorFinancialProfitLossRouteImport } from './routes/_administrator/financial/profit-loss'
import { Route as AdministratorFinancialPendingPayoutsRouteImport } from './routes/_administrator/financial/pending-payouts'
import { Route as AdministratorFinancialPayrollRouteImport } from './routes/_administrator/financial/payroll'
import { Route as AdministratorFinancialPaymentRouteImport } from './routes/_administrator/financial/payment'
import { Route as AdministratorFinancialInvoiceTemplatesRouteImport } from './routes/_administrator/financial/invoice-templates'
import { Route as AdministratorAdminSettingsRouteImport } from './routes/_administrator/admin/settings'
import { Route as AdministratorAdminScheduleRouteImport } from './routes/_administrator/admin/schedule'
import { Route as AdministratorAdminInboxRouteImport } from './routes/_administrator/admin/inbox'
import { Route as CommunitiesCodeTopicCodeIndexRouteImport } from './routes/communities/$code/$topicCode/index'
import { Route as AdministratorAdminDepartmentsIndexRouteImport } from './routes/_administrator/admin/departments/index'
import { Route as CommunitiesCodeTopicCodePostSlugRouteImport } from './routes/communities/$code/$topicCode/$postSlug'
import { Route as AdministratorAdminMgmtStaffDirectoryRouteImport } from './routes/_administrator/admin/mgmt/staff-directory'
import { Route as AdministratorAdminMgmtRevenueRouteImport } from './routes/_administrator/admin/mgmt/revenue'
import { Route as AdministratorAdminMgmtInviteMemberRouteImport } from './routes/_administrator/admin/mgmt/invite-member'
import { Route as AdministratorAdminMgmtAccessControlRouteImport } from './routes/_administrator/admin/mgmt/access-control'
import { Route as AdministratorAdminDepartmentsCodeRouteImport } from './routes/_administrator/admin/departments/$code'
import { Route as AdministratorAdminMgmtStaffDirectoryIndexRouteImport } from './routes/_administrator/admin/mgmt/staff-directory/index'
import { Route as AdministratorAdminMgmtJobsIndexRouteImport } from './routes/_administrator/admin/mgmt/jobs/index'
import { Route as AdministratorAdminMgmtFileDocsIndexRouteImport } from './routes/_administrator/admin/mgmt/file-docs/index'
import { Route as AdministratorAdminMgmtAccessControlIndexRouteImport } from './routes/_administrator/admin/mgmt/access-control/index'
import { Route as AdministratorAdminMgmtJobsNoRouteImport } from './routes/_administrator/admin/mgmt/jobs/$no'
import { Route as AdministratorAdminMgmtAccessControlPermissionsRouteImport } from './routes/_administrator/admin/mgmt/access-control/permissions'
import { Route as AdministratorAdminMgmtAccessControlMatrixRouteImport } from './routes/_administrator/admin/mgmt/access-control/matrix'
import { Route as AdministratorAdminMgmtAccessControlUsersIndexRouteImport } from './routes/_administrator/admin/mgmt/access-control/users/index'
import { Route as AdministratorAdminMgmtAccessControlRolesIndexRouteImport } from './routes/_administrator/admin/mgmt/access-control/roles/index'
import { Route as AdministratorAdminMgmtStaffDirectoryUsernameEditRouteImport } from './routes/_administrator/admin/mgmt/staff-directory/$username/edit'
import { Route as AdministratorAdminMgmtAccessControlUsersUsernameRouteImport } from './routes/_administrator/admin/mgmt/access-control/users/$username'
import { Route as AdministratorAdminMgmtAccessControlRolesCodeIndexRouteImport } from './routes/_administrator/admin/mgmt/access-control/roles/$code/index'
import { Route as AdministratorAdminMgmtAccessControlRolesCodePermMatrixRouteImport } from './routes/_administrator/admin/mgmt/access-control/roles/$code/perm-matrix'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/_administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMyProfileRoute = SettingsMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLoginAndSecurityRoute =
  SettingsLoginAndSecurityRouteImport.update({
    id: '/login-and-security',
    path: '/login-and-security',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsLanguageAndRegionRoute =
  SettingsLanguageAndRegionRouteImport.update({
    id: '/language-and-region',
    path: '/language-and-region',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkspaceTaskSummaryRoute = WorkspaceTaskSummaryRouteImport.update({
  id: '/task-summary',
  path: '/task-summary',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceScheduleRoute = WorkspaceScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectCenterRoute = WorkspaceProjectCenterRouteImport.update({
  id: '/project-center',
  path: '/project-center',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicHelpCenterRoute = PublicHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => PublicRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdministratorFinancialRoute = AdministratorFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdministratorRoute,
} as any)
const CommunitiesCodeIndexRoute = CommunitiesCodeIndexRouteImport.update({
  id: '/$code/',
  path: '/$code/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const WorkspaceProjectCenterIndexRoute =
  WorkspaceProjectCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectCenterRoute,
  } as any)
const WorkspaceJobsIndexRoute = WorkspaceJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkbenchIndexRoute = WorkspaceWorkbenchIndexRouteImport.update({
  id: '/_workbench/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AdministratorAdminIndexRoute = AdministratorAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdministratorRoute,
} as any)
const WorkspaceProjectCenterTabRoute =
  WorkspaceProjectCenterTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => WorkspaceProjectCenterRoute,
  } as any)
const WorkspaceJobsNoRoute = WorkspaceJobsNoRouteImport.update({
  id: '/jobs/$no',
  path: '/jobs/$no',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdministratorFinancialSettingRoute =
  AdministratorFinancialSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialReimbursementsRoute =
  AdministratorFinancialReimbursementsRouteImport.update({
    id: '/reimbursements',
    path: '/reimbursements',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialProfitLossRoute =
  AdministratorFinancialProfitLossRouteImport.update({
    id: '/profit-loss',
    path: '/profit-loss',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialPendingPayoutsRoute =
  AdministratorFinancialPendingPayoutsRouteImport.update({
    id: '/pending-payouts',
    path: '/pending-payouts',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialPayrollRoute =
  AdministratorFinancialPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialPaymentRoute =
  AdministratorFinancialPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorFinancialInvoiceTemplatesRoute =
  AdministratorFinancialInvoiceTemplatesRouteImport.update({
    id: '/invoice-templates',
    path: '/invoice-templates',
    getParentRoute: () => AdministratorFinancialRoute,
  } as any)
const AdministratorAdminSettingsRoute =
  AdministratorAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminScheduleRoute =
  AdministratorAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminInboxRoute = AdministratorAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AdministratorRoute,
} as any)
const CommunitiesCodeTopicCodeIndexRoute =
  CommunitiesCodeTopicCodeIndexRouteImport.update({
    id: '/$code/$topicCode/',
    path: '/$code/$topicCode/',
    getParentRoute: () => CommunitiesRoute,
  } as any)
const AdministratorAdminDepartmentsIndexRoute =
  AdministratorAdminDepartmentsIndexRouteImport.update({
    id: '/admin/departments/',
    path: '/admin/departments/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const CommunitiesCodeTopicCodePostSlugRoute =
  CommunitiesCodeTopicCodePostSlugRouteImport.update({
    id: '/$code/$topicCode/$postSlug',
    path: '/$code/$topicCode/$postSlug',
    getParentRoute: () => CommunitiesRoute,
  } as any)
const AdministratorAdminMgmtStaffDirectoryRoute =
  AdministratorAdminMgmtStaffDirectoryRouteImport.update({
    id: '/admin/mgmt/staff-directory',
    path: '/admin/mgmt/staff-directory',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtRevenueRoute =
  AdministratorAdminMgmtRevenueRouteImport.update({
    id: '/admin/mgmt/revenue',
    path: '/admin/mgmt/revenue',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtInviteMemberRoute =
  AdministratorAdminMgmtInviteMemberRouteImport.update({
    id: '/admin/mgmt/invite-member',
    path: '/admin/mgmt/invite-member',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtAccessControlRoute =
  AdministratorAdminMgmtAccessControlRouteImport.update({
    id: '/admin/mgmt/access-control',
    path: '/admin/mgmt/access-control',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminDepartmentsCodeRoute =
  AdministratorAdminDepartmentsCodeRouteImport.update({
    id: '/admin/departments/$code',
    path: '/admin/departments/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtStaffDirectoryIndexRoute =
  AdministratorAdminMgmtStaffDirectoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministratorAdminMgmtStaffDirectoryRoute,
  } as any)
const AdministratorAdminMgmtJobsIndexRoute =
  AdministratorAdminMgmtJobsIndexRouteImport.update({
    id: '/admin/mgmt/jobs/',
    path: '/admin/mgmt/jobs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtFileDocsIndexRoute =
  AdministratorAdminMgmtFileDocsIndexRouteImport.update({
    id: '/admin/mgmt/file-docs/',
    path: '/admin/mgmt/file-docs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtAccessControlIndexRoute =
  AdministratorAdminMgmtAccessControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtJobsNoRoute =
  AdministratorAdminMgmtJobsNoRouteImport.update({
    id: '/admin/mgmt/jobs/$no',
    path: '/admin/mgmt/jobs/$no',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminMgmtAccessControlPermissionsRoute =
  AdministratorAdminMgmtAccessControlPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtAccessControlMatrixRoute =
  AdministratorAdminMgmtAccessControlMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtAccessControlUsersIndexRoute =
  AdministratorAdminMgmtAccessControlUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtAccessControlRolesIndexRoute =
  AdministratorAdminMgmtAccessControlRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtStaffDirectoryUsernameEditRoute =
  AdministratorAdminMgmtStaffDirectoryUsernameEditRouteImport.update({
    id: '/$username/edit',
    path: '/$username/edit',
    getParentRoute: () => AdministratorAdminMgmtStaffDirectoryRoute,
  } as any)
const AdministratorAdminMgmtAccessControlUsersUsernameRoute =
  AdministratorAdminMgmtAccessControlUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtAccessControlRolesCodeIndexRoute =
  AdministratorAdminMgmtAccessControlRolesCodeIndexRouteImport.update({
    id: '/roles/$code/',
    path: '/roles/$code/',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)
const AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute =
  AdministratorAdminMgmtAccessControlRolesCodePermMatrixRouteImport.update({
    id: '/roles/$code/perm-matrix',
    path: '/roles/$code/perm-matrix',
    getParentRoute: () => AdministratorAdminMgmtAccessControlRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/communities': typeof CommunitiesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/financial': typeof AdministratorFinancialRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/project-center': typeof WorkspaceProjectCenterRouteWithChildren
  '/schedule': typeof WorkspaceScheduleRoute
  '/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/payment': typeof AdministratorFinancialPaymentRoute
  '/financial/payroll': typeof AdministratorFinancialPayrollRoute
  '/financial/pending-payouts': typeof AdministratorFinancialPendingPayoutsRoute
  '/financial/profit-loss': typeof AdministratorFinancialProfitLossRoute
  '/financial/reimbursements': typeof AdministratorFinancialReimbursementsRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin': typeof AdministratorAdminIndexRoute
  '/': typeof WorkspaceWorkbenchIndexRoute
  '/jobs': typeof WorkspaceJobsIndexRoute
  '/project-center/': typeof WorkspaceProjectCenterIndexRoute
  '/communities/$code': typeof CommunitiesCodeIndexRoute
  '/admin/departments/$code': typeof AdministratorAdminDepartmentsCodeRoute
  '/admin/mgmt/access-control': typeof AdministratorAdminMgmtAccessControlRouteWithChildren
  '/admin/mgmt/invite-member': typeof AdministratorAdminMgmtInviteMemberRoute
  '/admin/mgmt/revenue': typeof AdministratorAdminMgmtRevenueRoute
  '/admin/mgmt/staff-directory': typeof AdministratorAdminMgmtStaffDirectoryRouteWithChildren
  '/communities/$code/$topicCode/$postSlug': typeof CommunitiesCodeTopicCodePostSlugRoute
  '/admin/departments': typeof AdministratorAdminDepartmentsIndexRoute
  '/communities/$code/$topicCode': typeof CommunitiesCodeTopicCodeIndexRoute
  '/admin/mgmt/access-control/matrix': typeof AdministratorAdminMgmtAccessControlMatrixRoute
  '/admin/mgmt/access-control/permissions': typeof AdministratorAdminMgmtAccessControlPermissionsRoute
  '/admin/mgmt/jobs/$no': typeof AdministratorAdminMgmtJobsNoRoute
  '/admin/mgmt/access-control/': typeof AdministratorAdminMgmtAccessControlIndexRoute
  '/admin/mgmt/file-docs': typeof AdministratorAdminMgmtFileDocsIndexRoute
  '/admin/mgmt/jobs': typeof AdministratorAdminMgmtJobsIndexRoute
  '/admin/mgmt/staff-directory/': typeof AdministratorAdminMgmtStaffDirectoryIndexRoute
  '/admin/mgmt/access-control/users/$username': typeof AdministratorAdminMgmtAccessControlUsersUsernameRoute
  '/admin/mgmt/staff-directory/$username/edit': typeof AdministratorAdminMgmtStaffDirectoryUsernameEditRoute
  '/admin/mgmt/access-control/roles': typeof AdministratorAdminMgmtAccessControlRolesIndexRoute
  '/admin/mgmt/access-control/users': typeof AdministratorAdminMgmtAccessControlUsersIndexRoute
  '/admin/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute
  '/admin/mgmt/access-control/roles/$code': typeof AdministratorAdminMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesByTo {
  '/financial': typeof AdministratorFinancialRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/schedule': typeof WorkspaceScheduleRoute
  '/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/communities': typeof CommunitiesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/payment': typeof AdministratorFinancialPaymentRoute
  '/financial/payroll': typeof AdministratorFinancialPayrollRoute
  '/financial/pending-payouts': typeof AdministratorFinancialPendingPayoutsRoute
  '/financial/profit-loss': typeof AdministratorFinancialProfitLossRoute
  '/financial/reimbursements': typeof AdministratorFinancialReimbursementsRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin': typeof AdministratorAdminIndexRoute
  '/': typeof WorkspaceWorkbenchIndexRoute
  '/jobs': typeof WorkspaceJobsIndexRoute
  '/project-center': typeof WorkspaceProjectCenterIndexRoute
  '/communities/$code': typeof CommunitiesCodeIndexRoute
  '/admin/departments/$code': typeof AdministratorAdminDepartmentsCodeRoute
  '/admin/mgmt/invite-member': typeof AdministratorAdminMgmtInviteMemberRoute
  '/admin/mgmt/revenue': typeof AdministratorAdminMgmtRevenueRoute
  '/communities/$code/$topicCode/$postSlug': typeof CommunitiesCodeTopicCodePostSlugRoute
  '/admin/departments': typeof AdministratorAdminDepartmentsIndexRoute
  '/communities/$code/$topicCode': typeof CommunitiesCodeTopicCodeIndexRoute
  '/admin/mgmt/access-control/matrix': typeof AdministratorAdminMgmtAccessControlMatrixRoute
  '/admin/mgmt/access-control/permissions': typeof AdministratorAdminMgmtAccessControlPermissionsRoute
  '/admin/mgmt/jobs/$no': typeof AdministratorAdminMgmtJobsNoRoute
  '/admin/mgmt/access-control': typeof AdministratorAdminMgmtAccessControlIndexRoute
  '/admin/mgmt/file-docs': typeof AdministratorAdminMgmtFileDocsIndexRoute
  '/admin/mgmt/jobs': typeof AdministratorAdminMgmtJobsIndexRoute
  '/admin/mgmt/staff-directory': typeof AdministratorAdminMgmtStaffDirectoryIndexRoute
  '/admin/mgmt/access-control/users/$username': typeof AdministratorAdminMgmtAccessControlUsersUsernameRoute
  '/admin/mgmt/staff-directory/$username/edit': typeof AdministratorAdminMgmtStaffDirectoryUsernameEditRoute
  '/admin/mgmt/access-control/roles': typeof AdministratorAdminMgmtAccessControlRolesIndexRoute
  '/admin/mgmt/access-control/users': typeof AdministratorAdminMgmtAccessControlUsersIndexRoute
  '/admin/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute
  '/admin/mgmt/access-control/roles/$code': typeof AdministratorAdminMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_administrator': typeof AdministratorRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/communities': typeof CommunitiesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_administrator/financial': typeof AdministratorFinancialRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_public/help-center': typeof PublicHelpCenterRoute
  '/_workspace/overview': typeof WorkspaceOverviewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/project-center': typeof WorkspaceProjectCenterRouteWithChildren
  '/_workspace/schedule': typeof WorkspaceScheduleRoute
  '/_workspace/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_administrator/admin/inbox': typeof AdministratorAdminInboxRoute
  '/_administrator/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/_administrator/admin/settings': typeof AdministratorAdminSettingsRoute
  '/_administrator/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/_administrator/financial/payment': typeof AdministratorFinancialPaymentRoute
  '/_administrator/financial/payroll': typeof AdministratorFinancialPayrollRoute
  '/_administrator/financial/pending-payouts': typeof AdministratorFinancialPendingPayoutsRoute
  '/_administrator/financial/profit-loss': typeof AdministratorFinancialProfitLossRoute
  '/_administrator/financial/reimbursements': typeof AdministratorFinancialReimbursementsRoute
  '/_administrator/financial/setting': typeof AdministratorFinancialSettingRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/_workspace/jobs/$no': typeof WorkspaceJobsNoRoute
  '/_workspace/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/_administrator/admin/': typeof AdministratorAdminIndexRoute
  '/_workspace/_workbench/': typeof WorkspaceWorkbenchIndexRoute
  '/_workspace/jobs/': typeof WorkspaceJobsIndexRoute
  '/_workspace/project-center/': typeof WorkspaceProjectCenterIndexRoute
  '/communities/$code/': typeof CommunitiesCodeIndexRoute
  '/_administrator/admin/departments/$code': typeof AdministratorAdminDepartmentsCodeRoute
  '/_administrator/admin/mgmt/access-control': typeof AdministratorAdminMgmtAccessControlRouteWithChildren
  '/_administrator/admin/mgmt/invite-member': typeof AdministratorAdminMgmtInviteMemberRoute
  '/_administrator/admin/mgmt/revenue': typeof AdministratorAdminMgmtRevenueRoute
  '/_administrator/admin/mgmt/staff-directory': typeof AdministratorAdminMgmtStaffDirectoryRouteWithChildren
  '/communities/$code/$topicCode/$postSlug': typeof CommunitiesCodeTopicCodePostSlugRoute
  '/_administrator/admin/departments/': typeof AdministratorAdminDepartmentsIndexRoute
  '/communities/$code/$topicCode/': typeof CommunitiesCodeTopicCodeIndexRoute
  '/_administrator/admin/mgmt/access-control/matrix': typeof AdministratorAdminMgmtAccessControlMatrixRoute
  '/_administrator/admin/mgmt/access-control/permissions': typeof AdministratorAdminMgmtAccessControlPermissionsRoute
  '/_administrator/admin/mgmt/jobs/$no': typeof AdministratorAdminMgmtJobsNoRoute
  '/_administrator/admin/mgmt/access-control/': typeof AdministratorAdminMgmtAccessControlIndexRoute
  '/_administrator/admin/mgmt/file-docs/': typeof AdministratorAdminMgmtFileDocsIndexRoute
  '/_administrator/admin/mgmt/jobs/': typeof AdministratorAdminMgmtJobsIndexRoute
  '/_administrator/admin/mgmt/staff-directory/': typeof AdministratorAdminMgmtStaffDirectoryIndexRoute
  '/_administrator/admin/mgmt/access-control/users/$username': typeof AdministratorAdminMgmtAccessControlUsersUsernameRoute
  '/_administrator/admin/mgmt/staff-directory/$username/edit': typeof AdministratorAdminMgmtStaffDirectoryUsernameEditRoute
  '/_administrator/admin/mgmt/access-control/roles/': typeof AdministratorAdminMgmtAccessControlRolesIndexRoute
  '/_administrator/admin/mgmt/access-control/users/': typeof AdministratorAdminMgmtAccessControlUsersIndexRoute
  '/_administrator/admin/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute
  '/_administrator/admin/mgmt/access-control/roles/$code/': typeof AdministratorAdminMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/communities'
    | '/settings'
    | '/financial'
    | '/login'
    | '/help-center'
    | '/overview'
    | '/profile'
    | '/project-center'
    | '/schedule'
    | '/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/communities/'
    | '/settings/'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/financial/invoice-templates'
    | '/financial/payment'
    | '/financial/payroll'
    | '/financial/pending-payouts'
    | '/financial/profit-loss'
    | '/financial/reimbursements'
    | '/financial/setting'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin'
    | '/'
    | '/jobs'
    | '/project-center/'
    | '/communities/$code'
    | '/admin/departments/$code'
    | '/admin/mgmt/access-control'
    | '/admin/mgmt/invite-member'
    | '/admin/mgmt/revenue'
    | '/admin/mgmt/staff-directory'
    | '/communities/$code/$topicCode/$postSlug'
    | '/admin/departments'
    | '/communities/$code/$topicCode'
    | '/admin/mgmt/access-control/matrix'
    | '/admin/mgmt/access-control/permissions'
    | '/admin/mgmt/jobs/$no'
    | '/admin/mgmt/access-control/'
    | '/admin/mgmt/file-docs'
    | '/admin/mgmt/jobs'
    | '/admin/mgmt/staff-directory/'
    | '/admin/mgmt/access-control/users/$username'
    | '/admin/mgmt/staff-directory/$username/edit'
    | '/admin/mgmt/access-control/roles'
    | '/admin/mgmt/access-control/users'
    | '/admin/mgmt/access-control/roles/$code/perm-matrix'
    | '/admin/mgmt/access-control/roles/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/financial'
    | '/login'
    | '/help-center'
    | '/overview'
    | '/profile'
    | '/schedule'
    | '/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/communities'
    | '/settings'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/financial/invoice-templates'
    | '/financial/payment'
    | '/financial/payroll'
    | '/financial/pending-payouts'
    | '/financial/profit-loss'
    | '/financial/reimbursements'
    | '/financial/setting'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin'
    | '/'
    | '/jobs'
    | '/project-center'
    | '/communities/$code'
    | '/admin/departments/$code'
    | '/admin/mgmt/invite-member'
    | '/admin/mgmt/revenue'
    | '/communities/$code/$topicCode/$postSlug'
    | '/admin/departments'
    | '/communities/$code/$topicCode'
    | '/admin/mgmt/access-control/matrix'
    | '/admin/mgmt/access-control/permissions'
    | '/admin/mgmt/jobs/$no'
    | '/admin/mgmt/access-control'
    | '/admin/mgmt/file-docs'
    | '/admin/mgmt/jobs'
    | '/admin/mgmt/staff-directory'
    | '/admin/mgmt/access-control/users/$username'
    | '/admin/mgmt/staff-directory/$username/edit'
    | '/admin/mgmt/access-control/roles'
    | '/admin/mgmt/access-control/users'
    | '/admin/mgmt/access-control/roles/$code/perm-matrix'
    | '/admin/mgmt/access-control/roles/$code'
  id:
    | '__root__'
    | '/_administrator'
    | '/_auth'
    | '/_public'
    | '/_workspace'
    | '/communities'
    | '/settings'
    | '/_administrator/financial'
    | '/_auth/login'
    | '/_public/help-center'
    | '/_workspace/overview'
    | '/_workspace/profile'
    | '/_workspace/project-center'
    | '/_workspace/schedule'
    | '/_workspace/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/communities/'
    | '/settings/'
    | '/_administrator/admin/inbox'
    | '/_administrator/admin/schedule'
    | '/_administrator/admin/settings'
    | '/_administrator/financial/invoice-templates'
    | '/_administrator/financial/payment'
    | '/_administrator/financial/payroll'
    | '/_administrator/financial/pending-payouts'
    | '/_administrator/financial/profit-loss'
    | '/_administrator/financial/reimbursements'
    | '/_administrator/financial/setting'
    | '/_auth/auth/reset-password'
    | '/_workspace/jobs/$no'
    | '/_workspace/project-center/$tab'
    | '/_administrator/admin/'
    | '/_workspace/_workbench/'
    | '/_workspace/jobs/'
    | '/_workspace/project-center/'
    | '/communities/$code/'
    | '/_administrator/admin/departments/$code'
    | '/_administrator/admin/mgmt/access-control'
    | '/_administrator/admin/mgmt/invite-member'
    | '/_administrator/admin/mgmt/revenue'
    | '/_administrator/admin/mgmt/staff-directory'
    | '/communities/$code/$topicCode/$postSlug'
    | '/_administrator/admin/departments/'
    | '/communities/$code/$topicCode/'
    | '/_administrator/admin/mgmt/access-control/matrix'
    | '/_administrator/admin/mgmt/access-control/permissions'
    | '/_administrator/admin/mgmt/jobs/$no'
    | '/_administrator/admin/mgmt/access-control/'
    | '/_administrator/admin/mgmt/file-docs/'
    | '/_administrator/admin/mgmt/jobs/'
    | '/_administrator/admin/mgmt/staff-directory/'
    | '/_administrator/admin/mgmt/access-control/users/$username'
    | '/_administrator/admin/mgmt/staff-directory/$username/edit'
    | '/_administrator/admin/mgmt/access-control/roles/'
    | '/_administrator/admin/mgmt/access-control/users/'
    | '/_administrator/admin/mgmt/access-control/roles/$code/perm-matrix'
    | '/_administrator/admin/mgmt/access-control/roles/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdministratorRoute: typeof AdministratorRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_administrator': {
      id: '/_administrator'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/my-profile': {
      id: '/settings/my-profile'
      path: '/my-profile'
      fullPath: '/settings/my-profile'
      preLoaderRoute: typeof SettingsMyProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/login-and-security': {
      id: '/settings/login-and-security'
      path: '/login-and-security'
      fullPath: '/settings/login-and-security'
      preLoaderRoute: typeof SettingsLoginAndSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language-and-region': {
      id: '/settings/language-and-region'
      path: '/language-and-region'
      fullPath: '/settings/language-and-region'
      preLoaderRoute: typeof SettingsLanguageAndRegionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_workspace/task-summary': {
      id: '/_workspace/task-summary'
      path: '/task-summary'
      fullPath: '/task-summary'
      preLoaderRoute: typeof WorkspaceTaskSummaryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/schedule': {
      id: '/_workspace/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof WorkspaceScheduleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/project-center': {
      id: '/_workspace/project-center'
      path: '/project-center'
      fullPath: '/project-center'
      preLoaderRoute: typeof WorkspaceProjectCenterRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/overview': {
      id: '/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/help-center': {
      id: '/_public/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof PublicHelpCenterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_administrator/financial': {
      id: '/_administrator/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AdministratorFinancialRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/communities/$code/': {
      id: '/communities/$code/'
      path: '/$code'
      fullPath: '/communities/$code'
      preLoaderRoute: typeof CommunitiesCodeIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/_workspace/project-center/': {
      id: '/_workspace/project-center/'
      path: '/'
      fullPath: '/project-center/'
      preLoaderRoute: typeof WorkspaceProjectCenterIndexRouteImport
      parentRoute: typeof WorkspaceProjectCenterRoute
    }
    '/_workspace/jobs/': {
      id: '/_workspace/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof WorkspaceJobsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/_workbench/': {
      id: '/_workspace/_workbench/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceWorkbenchIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_administrator/admin/': {
      id: '/_administrator/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdministratorAdminIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_workspace/project-center/$tab': {
      id: '/_workspace/project-center/$tab'
      path: '/$tab'
      fullPath: '/project-center/$tab'
      preLoaderRoute: typeof WorkspaceProjectCenterTabRouteImport
      parentRoute: typeof WorkspaceProjectCenterRoute
    }
    '/_workspace/jobs/$no': {
      id: '/_workspace/jobs/$no'
      path: '/jobs/$no'
      fullPath: '/jobs/$no'
      preLoaderRoute: typeof WorkspaceJobsNoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_administrator/financial/setting': {
      id: '/_administrator/financial/setting'
      path: '/setting'
      fullPath: '/financial/setting'
      preLoaderRoute: typeof AdministratorFinancialSettingRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/reimbursements': {
      id: '/_administrator/financial/reimbursements'
      path: '/reimbursements'
      fullPath: '/financial/reimbursements'
      preLoaderRoute: typeof AdministratorFinancialReimbursementsRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/profit-loss': {
      id: '/_administrator/financial/profit-loss'
      path: '/profit-loss'
      fullPath: '/financial/profit-loss'
      preLoaderRoute: typeof AdministratorFinancialProfitLossRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/pending-payouts': {
      id: '/_administrator/financial/pending-payouts'
      path: '/pending-payouts'
      fullPath: '/financial/pending-payouts'
      preLoaderRoute: typeof AdministratorFinancialPendingPayoutsRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/payroll': {
      id: '/_administrator/financial/payroll'
      path: '/payroll'
      fullPath: '/financial/payroll'
      preLoaderRoute: typeof AdministratorFinancialPayrollRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/payment': {
      id: '/_administrator/financial/payment'
      path: '/payment'
      fullPath: '/financial/payment'
      preLoaderRoute: typeof AdministratorFinancialPaymentRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/financial/invoice-templates': {
      id: '/_administrator/financial/invoice-templates'
      path: '/invoice-templates'
      fullPath: '/financial/invoice-templates'
      preLoaderRoute: typeof AdministratorFinancialInvoiceTemplatesRouteImport
      parentRoute: typeof AdministratorFinancialRoute
    }
    '/_administrator/admin/settings': {
      id: '/_administrator/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdministratorAdminSettingsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/schedule': {
      id: '/_administrator/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdministratorAdminScheduleRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/inbox': {
      id: '/_administrator/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdministratorAdminInboxRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/communities/$code/$topicCode/': {
      id: '/communities/$code/$topicCode/'
      path: '/$code/$topicCode'
      fullPath: '/communities/$code/$topicCode'
      preLoaderRoute: typeof CommunitiesCodeTopicCodeIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/_administrator/admin/departments/': {
      id: '/_administrator/admin/departments/'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdministratorAdminDepartmentsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/communities/$code/$topicCode/$postSlug': {
      id: '/communities/$code/$topicCode/$postSlug'
      path: '/$code/$topicCode/$postSlug'
      fullPath: '/communities/$code/$topicCode/$postSlug'
      preLoaderRoute: typeof CommunitiesCodeTopicCodePostSlugRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/_administrator/admin/mgmt/staff-directory': {
      id: '/_administrator/admin/mgmt/staff-directory'
      path: '/admin/mgmt/staff-directory'
      fullPath: '/admin/mgmt/staff-directory'
      preLoaderRoute: typeof AdministratorAdminMgmtStaffDirectoryRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/revenue': {
      id: '/_administrator/admin/mgmt/revenue'
      path: '/admin/mgmt/revenue'
      fullPath: '/admin/mgmt/revenue'
      preLoaderRoute: typeof AdministratorAdminMgmtRevenueRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/invite-member': {
      id: '/_administrator/admin/mgmt/invite-member'
      path: '/admin/mgmt/invite-member'
      fullPath: '/admin/mgmt/invite-member'
      preLoaderRoute: typeof AdministratorAdminMgmtInviteMemberRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/access-control': {
      id: '/_administrator/admin/mgmt/access-control'
      path: '/admin/mgmt/access-control'
      fullPath: '/admin/mgmt/access-control'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/departments/$code': {
      id: '/_administrator/admin/departments/$code'
      path: '/admin/departments/$code'
      fullPath: '/admin/departments/$code'
      preLoaderRoute: typeof AdministratorAdminDepartmentsCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/staff-directory/': {
      id: '/_administrator/admin/mgmt/staff-directory/'
      path: '/'
      fullPath: '/admin/mgmt/staff-directory/'
      preLoaderRoute: typeof AdministratorAdminMgmtStaffDirectoryIndexRouteImport
      parentRoute: typeof AdministratorAdminMgmtStaffDirectoryRoute
    }
    '/_administrator/admin/mgmt/jobs/': {
      id: '/_administrator/admin/mgmt/jobs/'
      path: '/admin/mgmt/jobs'
      fullPath: '/admin/mgmt/jobs'
      preLoaderRoute: typeof AdministratorAdminMgmtJobsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/file-docs/': {
      id: '/_administrator/admin/mgmt/file-docs/'
      path: '/admin/mgmt/file-docs'
      fullPath: '/admin/mgmt/file-docs'
      preLoaderRoute: typeof AdministratorAdminMgmtFileDocsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/access-control/': {
      id: '/_administrator/admin/mgmt/access-control/'
      path: '/'
      fullPath: '/admin/mgmt/access-control/'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlIndexRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/jobs/$no': {
      id: '/_administrator/admin/mgmt/jobs/$no'
      path: '/admin/mgmt/jobs/$no'
      fullPath: '/admin/mgmt/jobs/$no'
      preLoaderRoute: typeof AdministratorAdminMgmtJobsNoRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/mgmt/access-control/permissions': {
      id: '/_administrator/admin/mgmt/access-control/permissions'
      path: '/permissions'
      fullPath: '/admin/mgmt/access-control/permissions'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlPermissionsRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/access-control/matrix': {
      id: '/_administrator/admin/mgmt/access-control/matrix'
      path: '/matrix'
      fullPath: '/admin/mgmt/access-control/matrix'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlMatrixRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/access-control/users/': {
      id: '/_administrator/admin/mgmt/access-control/users/'
      path: '/users'
      fullPath: '/admin/mgmt/access-control/users'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlUsersIndexRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/access-control/roles/': {
      id: '/_administrator/admin/mgmt/access-control/roles/'
      path: '/roles'
      fullPath: '/admin/mgmt/access-control/roles'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlRolesIndexRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/staff-directory/$username/edit': {
      id: '/_administrator/admin/mgmt/staff-directory/$username/edit'
      path: '/$username/edit'
      fullPath: '/admin/mgmt/staff-directory/$username/edit'
      preLoaderRoute: typeof AdministratorAdminMgmtStaffDirectoryUsernameEditRouteImport
      parentRoute: typeof AdministratorAdminMgmtStaffDirectoryRoute
    }
    '/_administrator/admin/mgmt/access-control/users/$username': {
      id: '/_administrator/admin/mgmt/access-control/users/$username'
      path: '/users/$username'
      fullPath: '/admin/mgmt/access-control/users/$username'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlUsersUsernameRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/access-control/roles/$code/': {
      id: '/_administrator/admin/mgmt/access-control/roles/$code/'
      path: '/roles/$code'
      fullPath: '/admin/mgmt/access-control/roles/$code'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlRolesCodeIndexRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
    '/_administrator/admin/mgmt/access-control/roles/$code/perm-matrix': {
      id: '/_administrator/admin/mgmt/access-control/roles/$code/perm-matrix'
      path: '/roles/$code/perm-matrix'
      fullPath: '/admin/mgmt/access-control/roles/$code/perm-matrix'
      preLoaderRoute: typeof AdministratorAdminMgmtAccessControlRolesCodePermMatrixRouteImport
      parentRoute: typeof AdministratorAdminMgmtAccessControlRoute
    }
  }
}

interface AdministratorFinancialRouteChildren {
  AdministratorFinancialInvoiceTemplatesRoute: typeof AdministratorFinancialInvoiceTemplatesRoute
  AdministratorFinancialPaymentRoute: typeof AdministratorFinancialPaymentRoute
  AdministratorFinancialPayrollRoute: typeof AdministratorFinancialPayrollRoute
  AdministratorFinancialPendingPayoutsRoute: typeof AdministratorFinancialPendingPayoutsRoute
  AdministratorFinancialProfitLossRoute: typeof AdministratorFinancialProfitLossRoute
  AdministratorFinancialReimbursementsRoute: typeof AdministratorFinancialReimbursementsRoute
  AdministratorFinancialSettingRoute: typeof AdministratorFinancialSettingRoute
}

const AdministratorFinancialRouteChildren: AdministratorFinancialRouteChildren =
  {
    AdministratorFinancialInvoiceTemplatesRoute:
      AdministratorFinancialInvoiceTemplatesRoute,
    AdministratorFinancialPaymentRoute: AdministratorFinancialPaymentRoute,
    AdministratorFinancialPayrollRoute: AdministratorFinancialPayrollRoute,
    AdministratorFinancialPendingPayoutsRoute:
      AdministratorFinancialPendingPayoutsRoute,
    AdministratorFinancialProfitLossRoute:
      AdministratorFinancialProfitLossRoute,
    AdministratorFinancialReimbursementsRoute:
      AdministratorFinancialReimbursementsRoute,
    AdministratorFinancialSettingRoute: AdministratorFinancialSettingRoute,
  }

const AdministratorFinancialRouteWithChildren =
  AdministratorFinancialRoute._addFileChildren(
    AdministratorFinancialRouteChildren,
  )

interface AdministratorAdminMgmtAccessControlRouteChildren {
  AdministratorAdminMgmtAccessControlMatrixRoute: typeof AdministratorAdminMgmtAccessControlMatrixRoute
  AdministratorAdminMgmtAccessControlPermissionsRoute: typeof AdministratorAdminMgmtAccessControlPermissionsRoute
  AdministratorAdminMgmtAccessControlIndexRoute: typeof AdministratorAdminMgmtAccessControlIndexRoute
  AdministratorAdminMgmtAccessControlUsersUsernameRoute: typeof AdministratorAdminMgmtAccessControlUsersUsernameRoute
  AdministratorAdminMgmtAccessControlRolesIndexRoute: typeof AdministratorAdminMgmtAccessControlRolesIndexRoute
  AdministratorAdminMgmtAccessControlUsersIndexRoute: typeof AdministratorAdminMgmtAccessControlUsersIndexRoute
  AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute: typeof AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute
  AdministratorAdminMgmtAccessControlRolesCodeIndexRoute: typeof AdministratorAdminMgmtAccessControlRolesCodeIndexRoute
}

const AdministratorAdminMgmtAccessControlRouteChildren: AdministratorAdminMgmtAccessControlRouteChildren =
  {
    AdministratorAdminMgmtAccessControlMatrixRoute:
      AdministratorAdminMgmtAccessControlMatrixRoute,
    AdministratorAdminMgmtAccessControlPermissionsRoute:
      AdministratorAdminMgmtAccessControlPermissionsRoute,
    AdministratorAdminMgmtAccessControlIndexRoute:
      AdministratorAdminMgmtAccessControlIndexRoute,
    AdministratorAdminMgmtAccessControlUsersUsernameRoute:
      AdministratorAdminMgmtAccessControlUsersUsernameRoute,
    AdministratorAdminMgmtAccessControlRolesIndexRoute:
      AdministratorAdminMgmtAccessControlRolesIndexRoute,
    AdministratorAdminMgmtAccessControlUsersIndexRoute:
      AdministratorAdminMgmtAccessControlUsersIndexRoute,
    AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute:
      AdministratorAdminMgmtAccessControlRolesCodePermMatrixRoute,
    AdministratorAdminMgmtAccessControlRolesCodeIndexRoute:
      AdministratorAdminMgmtAccessControlRolesCodeIndexRoute,
  }

const AdministratorAdminMgmtAccessControlRouteWithChildren =
  AdministratorAdminMgmtAccessControlRoute._addFileChildren(
    AdministratorAdminMgmtAccessControlRouteChildren,
  )

interface AdministratorAdminMgmtStaffDirectoryRouteChildren {
  AdministratorAdminMgmtStaffDirectoryIndexRoute: typeof AdministratorAdminMgmtStaffDirectoryIndexRoute
  AdministratorAdminMgmtStaffDirectoryUsernameEditRoute: typeof AdministratorAdminMgmtStaffDirectoryUsernameEditRoute
}

const AdministratorAdminMgmtStaffDirectoryRouteChildren: AdministratorAdminMgmtStaffDirectoryRouteChildren =
  {
    AdministratorAdminMgmtStaffDirectoryIndexRoute:
      AdministratorAdminMgmtStaffDirectoryIndexRoute,
    AdministratorAdminMgmtStaffDirectoryUsernameEditRoute:
      AdministratorAdminMgmtStaffDirectoryUsernameEditRoute,
  }

const AdministratorAdminMgmtStaffDirectoryRouteWithChildren =
  AdministratorAdminMgmtStaffDirectoryRoute._addFileChildren(
    AdministratorAdminMgmtStaffDirectoryRouteChildren,
  )

interface AdministratorRouteChildren {
  AdministratorFinancialRoute: typeof AdministratorFinancialRouteWithChildren
  AdministratorAdminInboxRoute: typeof AdministratorAdminInboxRoute
  AdministratorAdminScheduleRoute: typeof AdministratorAdminScheduleRoute
  AdministratorAdminSettingsRoute: typeof AdministratorAdminSettingsRoute
  AdministratorAdminIndexRoute: typeof AdministratorAdminIndexRoute
  AdministratorAdminDepartmentsCodeRoute: typeof AdministratorAdminDepartmentsCodeRoute
  AdministratorAdminMgmtAccessControlRoute: typeof AdministratorAdminMgmtAccessControlRouteWithChildren
  AdministratorAdminMgmtInviteMemberRoute: typeof AdministratorAdminMgmtInviteMemberRoute
  AdministratorAdminMgmtRevenueRoute: typeof AdministratorAdminMgmtRevenueRoute
  AdministratorAdminMgmtStaffDirectoryRoute: typeof AdministratorAdminMgmtStaffDirectoryRouteWithChildren
  AdministratorAdminDepartmentsIndexRoute: typeof AdministratorAdminDepartmentsIndexRoute
  AdministratorAdminMgmtJobsNoRoute: typeof AdministratorAdminMgmtJobsNoRoute
  AdministratorAdminMgmtFileDocsIndexRoute: typeof AdministratorAdminMgmtFileDocsIndexRoute
  AdministratorAdminMgmtJobsIndexRoute: typeof AdministratorAdminMgmtJobsIndexRoute
}

const AdministratorRouteChildren: AdministratorRouteChildren = {
  AdministratorFinancialRoute: AdministratorFinancialRouteWithChildren,
  AdministratorAdminInboxRoute: AdministratorAdminInboxRoute,
  AdministratorAdminScheduleRoute: AdministratorAdminScheduleRoute,
  AdministratorAdminSettingsRoute: AdministratorAdminSettingsRoute,
  AdministratorAdminIndexRoute: AdministratorAdminIndexRoute,
  AdministratorAdminDepartmentsCodeRoute:
    AdministratorAdminDepartmentsCodeRoute,
  AdministratorAdminMgmtAccessControlRoute:
    AdministratorAdminMgmtAccessControlRouteWithChildren,
  AdministratorAdminMgmtInviteMemberRoute:
    AdministratorAdminMgmtInviteMemberRoute,
  AdministratorAdminMgmtRevenueRoute: AdministratorAdminMgmtRevenueRoute,
  AdministratorAdminMgmtStaffDirectoryRoute:
    AdministratorAdminMgmtStaffDirectoryRouteWithChildren,
  AdministratorAdminDepartmentsIndexRoute:
    AdministratorAdminDepartmentsIndexRoute,
  AdministratorAdminMgmtJobsNoRoute: AdministratorAdminMgmtJobsNoRoute,
  AdministratorAdminMgmtFileDocsIndexRoute:
    AdministratorAdminMgmtFileDocsIndexRoute,
  AdministratorAdminMgmtJobsIndexRoute: AdministratorAdminMgmtJobsIndexRoute,
}

const AdministratorRouteWithChildren = AdministratorRoute._addFileChildren(
  AdministratorRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicHelpCenterRoute: typeof PublicHelpCenterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHelpCenterRoute: PublicHelpCenterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceProjectCenterRouteChildren {
  WorkspaceProjectCenterTabRoute: typeof WorkspaceProjectCenterTabRoute
  WorkspaceProjectCenterIndexRoute: typeof WorkspaceProjectCenterIndexRoute
}

const WorkspaceProjectCenterRouteChildren: WorkspaceProjectCenterRouteChildren =
  {
    WorkspaceProjectCenterTabRoute: WorkspaceProjectCenterTabRoute,
    WorkspaceProjectCenterIndexRoute: WorkspaceProjectCenterIndexRoute,
  }

const WorkspaceProjectCenterRouteWithChildren =
  WorkspaceProjectCenterRoute._addFileChildren(
    WorkspaceProjectCenterRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceProjectCenterRoute: typeof WorkspaceProjectCenterRouteWithChildren
  WorkspaceScheduleRoute: typeof WorkspaceScheduleRoute
  WorkspaceTaskSummaryRoute: typeof WorkspaceTaskSummaryRoute
  WorkspaceJobsNoRoute: typeof WorkspaceJobsNoRoute
  WorkspaceWorkbenchIndexRoute: typeof WorkspaceWorkbenchIndexRoute
  WorkspaceJobsIndexRoute: typeof WorkspaceJobsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceProjectCenterRoute: WorkspaceProjectCenterRouteWithChildren,
  WorkspaceScheduleRoute: WorkspaceScheduleRoute,
  WorkspaceTaskSummaryRoute: WorkspaceTaskSummaryRoute,
  WorkspaceJobsNoRoute: WorkspaceJobsNoRoute,
  WorkspaceWorkbenchIndexRoute: WorkspaceWorkbenchIndexRoute,
  WorkspaceJobsIndexRoute: WorkspaceJobsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface CommunitiesRouteChildren {
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  CommunitiesCodeIndexRoute: typeof CommunitiesCodeIndexRoute
  CommunitiesCodeTopicCodePostSlugRoute: typeof CommunitiesCodeTopicCodePostSlugRoute
  CommunitiesCodeTopicCodeIndexRoute: typeof CommunitiesCodeTopicCodeIndexRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  CommunitiesCodeIndexRoute: CommunitiesCodeIndexRoute,
  CommunitiesCodeTopicCodePostSlugRoute: CommunitiesCodeTopicCodePostSlugRoute,
  CommunitiesCodeTopicCodeIndexRoute: CommunitiesCodeTopicCodeIndexRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLanguageAndRegionRoute: typeof SettingsLanguageAndRegionRoute
  SettingsLoginAndSecurityRoute: typeof SettingsLoginAndSecurityRoute
  SettingsMyProfileRoute: typeof SettingsMyProfileRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageAndRegionRoute: SettingsLanguageAndRegionRoute,
  SettingsLoginAndSecurityRoute: SettingsLoginAndSecurityRoute,
  SettingsMyProfileRoute: SettingsMyProfileRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdministratorRoute: AdministratorRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
