/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './presentation/routes/__root'
import { Route as SettingsRouteImport } from './presentation/routes/settings'
import { Route as WorkspaceRouteImport } from './presentation/routes/_workspace'
import { Route as PublicRouteImport } from './presentation/routes/_public'
import { Route as AuthenticationRouteImport } from './presentation/routes/_authentication'
import { Route as AdministratorRouteImport } from './presentation/routes/_administrator'
import { Route as SettingsIndexRouteImport } from './presentation/routes/settings/index'
import { Route as SettingsNotificationsRouteImport } from './presentation/routes/settings/notifications'
import { Route as SettingsMyProfileRouteImport } from './presentation/routes/settings/my-profile'
import { Route as SettingsLoginAndSecurityRouteImport } from './presentation/routes/settings/login-and-security'
import { Route as SettingsAppearanceRouteImport } from './presentation/routes/settings/appearance'
import { Route as WorkspaceScheduleRouteImport } from './presentation/routes/_workspace/schedule'
import { Route as WorkspaceProfileRouteImport } from './presentation/routes/_workspace/profile'
import { Route as WorkspaceOverviewRouteImport } from './presentation/routes/_workspace/overview'
import { Route as WorkspaceNotificationsRouteImport } from './presentation/routes/_workspace/notifications'
import { Route as WorkspaceWorkbenchRouteImport } from './presentation/routes/_workspace/_workbench'
import { Route as PublicHelpCenterRouteImport } from './presentation/routes/_public/help-center'
import { Route as AuthenticationLoginRouteImport } from './presentation/routes/_authentication/login'
import { Route as AdministratorFinancialIndexRouteImport } from './presentation/routes/_administrator/financial/index'
import { Route as AdministratorAdminIndexRouteImport } from './presentation/routes/_administrator/admin/index'
import { Route as WorkspaceProjectCenterTabRouteImport } from './presentation/routes/_workspace/project-center.$tab'
import { Route as WorkspaceJobsNoRouteImport } from './presentation/routes/_workspace/jobs.$no'
import { Route as AuthenticationAuthResetPasswordRouteImport } from './presentation/routes/_authentication/auth.reset-password'
import { Route as AdministratorMgmtRevenueRouteImport } from './presentation/routes/_administrator/mgmt/revenue'
import { Route as AdministratorMgmtAccessControlRouteImport } from './presentation/routes/_administrator/mgmt/access-control'
import { Route as AdministratorFinancialSettingRouteImport } from './presentation/routes/_administrator/financial/setting'
import { Route as AdministratorFinancialReceivablesRouteImport } from './presentation/routes/_administrator/financial/receivables'
import { Route as AdministratorFinancialPaymentChannelsRouteImport } from './presentation/routes/_administrator/financial/payment-channels'
import { Route as AdministratorFinancialInvoiceTemplatesRouteImport } from './presentation/routes/_administrator/financial/invoice-templates'
import { Route as AdministratorAdministratorMoreRouteImport } from './presentation/routes/_administrator/administrator.more'
import { Route as AdministratorAdminSettingsRouteImport } from './presentation/routes/_administrator/admin/settings'
import { Route as AdministratorAdminScheduleRouteImport } from './presentation/routes/_administrator/admin/schedule'
import { Route as AdministratorAdminInboxRouteImport } from './presentation/routes/_administrator/admin/inbox'
import { Route as AdministratorMgmtStaffDirectoryIndexRouteImport } from './presentation/routes/_administrator/mgmt/staff-directory/index'
import { Route as AdministratorMgmtJobsIndexRouteImport } from './presentation/routes/_administrator/mgmt/jobs/index'
import { Route as AdministratorMgmtJobTypesIndexRouteImport } from './presentation/routes/_administrator/mgmt/job-types/index'
import { Route as AdministratorMgmtJobTitlesIndexRouteImport } from './presentation/routes/_administrator/mgmt/job-titles/index'
import { Route as AdministratorMgmtFileDocsIndexRouteImport } from './presentation/routes/_administrator/mgmt/file-docs/index'
import { Route as AdministratorMgmtDepartmentsIndexRouteImport } from './presentation/routes/_administrator/mgmt/departments/index'
import { Route as AdministratorMgmtClientsIndexRouteImport } from './presentation/routes/_administrator/mgmt/clients/index'
import { Route as AdministratorMgmtAccessControlIndexRouteImport } from './presentation/routes/_administrator/mgmt/access-control/index'
import { Route as AdministratorFinancialPayoutsIndexRouteImport } from './presentation/routes/_administrator/financial/payouts/index'
import { Route as AdministratorFinancialLedgerIndexRouteImport } from './presentation/routes/_administrator/financial/ledger/index'
import { Route as AdministratorMgmtStaffDirectoryCodeRouteImport } from './presentation/routes/_administrator/mgmt/staff-directory/$code'
import { Route as AdministratorMgmtJobsCreateRouteImport } from './presentation/routes/_administrator/mgmt/jobs/create'
import { Route as AdministratorMgmtJobsNoRouteImport } from './presentation/routes/_administrator/mgmt/jobs/$no'
import { Route as AdministratorMgmtJobTypesIdRouteImport } from './presentation/routes/_administrator/mgmt/job-types/$id'
import { Route as AdministratorMgmtJobTitlesCodeRouteImport } from './presentation/routes/_administrator/mgmt/job-titles/$code'
import { Route as AdministratorMgmtDepartmentsCodeRouteImport } from './presentation/routes/_administrator/mgmt/departments/$code'
import { Route as AdministratorMgmtClientsCodeRouteImport } from './presentation/routes/_administrator/mgmt/clients/$code'
import { Route as AdministratorMgmtAccessControlPermissionsRouteImport } from './presentation/routes/_administrator/mgmt/access-control/permissions'
import { Route as AdministratorFinancialPayoutsNoRouteImport } from './presentation/routes/_administrator/financial/payouts/$no'
import { Route as AdministratorFinancialLedgerIdRouteImport } from './presentation/routes/_administrator/financial/ledger/$id'
import { Route as AdministratorMgmtJobsFolderTemplatesIndexRouteImport } from './presentation/routes/_administrator/mgmt/jobs/folder-templates/index'
import { Route as AdministratorMgmtJobsFolderTemplatesIdRouteImport } from './presentation/routes/_administrator/mgmt/jobs/folder-templates/$id'
import { Route as AdministratorMgmtAccessControlRolesCodeIndexRouteImport } from './presentation/routes/_administrator/mgmt/access-control/roles/$code/index'
import { Route as AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport } from './presentation/routes/_administrator/mgmt/access-control/roles/$code/perm-matrix'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/_administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMyProfileRoute = SettingsMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLoginAndSecurityRoute =
  SettingsLoginAndSecurityRouteImport.update({
    id: '/login-and-security',
    path: '/login-and-security',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkspaceScheduleRoute = WorkspaceScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNotificationsRoute = WorkspaceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkbenchRoute = WorkspaceWorkbenchRouteImport.update({
  id: '/_workbench',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicHelpCenterRoute = PublicHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AdministratorFinancialIndexRoute =
  AdministratorFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminIndexRoute = AdministratorAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdministratorRoute,
} as any)
const WorkspaceProjectCenterTabRoute =
  WorkspaceProjectCenterTabRouteImport.update({
    id: '/project-center/$tab',
    path: '/project-center/$tab',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceJobsNoRoute = WorkspaceJobsNoRouteImport.update({
  id: '/jobs/$no',
  path: '/jobs/$no',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AuthenticationAuthResetPasswordRoute =
  AuthenticationAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => AuthenticationRoute,
  } as any)
const AdministratorMgmtRevenueRoute =
  AdministratorMgmtRevenueRouteImport.update({
    id: '/mgmt/revenue',
    path: '/mgmt/revenue',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlRoute =
  AdministratorMgmtAccessControlRouteImport.update({
    id: '/mgmt/access-control',
    path: '/mgmt/access-control',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialSettingRoute =
  AdministratorFinancialSettingRouteImport.update({
    id: '/financial/setting',
    path: '/financial/setting',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialReceivablesRoute =
  AdministratorFinancialReceivablesRouteImport.update({
    id: '/financial/receivables',
    path: '/financial/receivables',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialPaymentChannelsRoute =
  AdministratorFinancialPaymentChannelsRouteImport.update({
    id: '/financial/payment-channels',
    path: '/financial/payment-channels',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialInvoiceTemplatesRoute =
  AdministratorFinancialInvoiceTemplatesRouteImport.update({
    id: '/financial/invoice-templates',
    path: '/financial/invoice-templates',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdministratorMoreRoute =
  AdministratorAdministratorMoreRouteImport.update({
    id: '/administrator/more',
    path: '/administrator/more',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminSettingsRoute =
  AdministratorAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminScheduleRoute =
  AdministratorAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminInboxRoute = AdministratorAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMgmtStaffDirectoryIndexRoute =
  AdministratorMgmtStaffDirectoryIndexRouteImport.update({
    id: '/mgmt/staff-directory/',
    path: '/mgmt/staff-directory/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsIndexRoute =
  AdministratorMgmtJobsIndexRouteImport.update({
    id: '/mgmt/jobs/',
    path: '/mgmt/jobs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobTypesIndexRoute =
  AdministratorMgmtJobTypesIndexRouteImport.update({
    id: '/mgmt/job-types/',
    path: '/mgmt/job-types/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobTitlesIndexRoute =
  AdministratorMgmtJobTitlesIndexRouteImport.update({
    id: '/mgmt/job-titles/',
    path: '/mgmt/job-titles/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtFileDocsIndexRoute =
  AdministratorMgmtFileDocsIndexRouteImport.update({
    id: '/mgmt/file-docs/',
    path: '/mgmt/file-docs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtDepartmentsIndexRoute =
  AdministratorMgmtDepartmentsIndexRouteImport.update({
    id: '/mgmt/departments/',
    path: '/mgmt/departments/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtClientsIndexRoute =
  AdministratorMgmtClientsIndexRouteImport.update({
    id: '/mgmt/clients/',
    path: '/mgmt/clients/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlIndexRoute =
  AdministratorMgmtAccessControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorFinancialPayoutsIndexRoute =
  AdministratorFinancialPayoutsIndexRouteImport.update({
    id: '/financial/payouts/',
    path: '/financial/payouts/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialLedgerIndexRoute =
  AdministratorFinancialLedgerIndexRouteImport.update({
    id: '/financial/ledger/',
    path: '/financial/ledger/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtStaffDirectoryCodeRoute =
  AdministratorMgmtStaffDirectoryCodeRouteImport.update({
    id: '/mgmt/staff-directory/$code',
    path: '/mgmt/staff-directory/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsCreateRoute =
  AdministratorMgmtJobsCreateRouteImport.update({
    id: '/mgmt/jobs/create',
    path: '/mgmt/jobs/create',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsNoRoute = AdministratorMgmtJobsNoRouteImport.update({
  id: '/mgmt/jobs/$no',
  path: '/mgmt/jobs/$no',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMgmtJobTypesIdRoute =
  AdministratorMgmtJobTypesIdRouteImport.update({
    id: '/mgmt/job-types/$id',
    path: '/mgmt/job-types/$id',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobTitlesCodeRoute =
  AdministratorMgmtJobTitlesCodeRouteImport.update({
    id: '/mgmt/job-titles/$code',
    path: '/mgmt/job-titles/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtDepartmentsCodeRoute =
  AdministratorMgmtDepartmentsCodeRouteImport.update({
    id: '/mgmt/departments/$code',
    path: '/mgmt/departments/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtClientsCodeRoute =
  AdministratorMgmtClientsCodeRouteImport.update({
    id: '/mgmt/clients/$code',
    path: '/mgmt/clients/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlPermissionsRoute =
  AdministratorMgmtAccessControlPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorFinancialPayoutsNoRoute =
  AdministratorFinancialPayoutsNoRouteImport.update({
    id: '/financial/payouts/$no',
    path: '/financial/payouts/$no',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialLedgerIdRoute =
  AdministratorFinancialLedgerIdRouteImport.update({
    id: '/financial/ledger/$id',
    path: '/financial/ledger/$id',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsFolderTemplatesIndexRoute =
  AdministratorMgmtJobsFolderTemplatesIndexRouteImport.update({
    id: '/mgmt/jobs/folder-templates/',
    path: '/mgmt/jobs/folder-templates/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsFolderTemplatesIdRoute =
  AdministratorMgmtJobsFolderTemplatesIdRouteImport.update({
    id: '/mgmt/jobs/folder-templates/$id',
    path: '/mgmt/jobs/folder-templates/$id',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlRolesCodeIndexRoute =
  AdministratorMgmtAccessControlRolesCodeIndexRouteImport.update({
    id: '/roles/$code/',
    path: '/roles/$code/',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorMgmtAccessControlRolesCodePermMatrixRoute =
  AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport.update({
    id: '/roles/$code/perm-matrix',
    path: '/roles/$code/perm-matrix',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceWorkbenchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/login': typeof AuthenticationLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/schedule': typeof WorkspaceScheduleRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/administrator/more': typeof AdministratorAdministratorMoreRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/mgmt/access-control': typeof AdministratorMgmtAccessControlRouteWithChildren
  '/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin/': typeof AdministratorAdminIndexRoute
  '/financial/': typeof AdministratorFinancialIndexRoute
  '/financial/ledger/$id': typeof AdministratorFinancialLedgerIdRoute
  '/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/mgmt/job-titles/$code': typeof AdministratorMgmtJobTitlesCodeRoute
  '/mgmt/job-types/$id': typeof AdministratorMgmtJobTypesIdRoute
  '/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/mgmt/jobs/create': typeof AdministratorMgmtJobsCreateRoute
  '/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/financial/ledger/': typeof AdministratorFinancialLedgerIndexRoute
  '/financial/payouts/': typeof AdministratorFinancialPayoutsIndexRoute
  '/mgmt/access-control/': typeof AdministratorMgmtAccessControlIndexRoute
  '/mgmt/clients/': typeof AdministratorMgmtClientsIndexRoute
  '/mgmt/departments/': typeof AdministratorMgmtDepartmentsIndexRoute
  '/mgmt/file-docs/': typeof AdministratorMgmtFileDocsIndexRoute
  '/mgmt/job-titles/': typeof AdministratorMgmtJobTitlesIndexRoute
  '/mgmt/job-types/': typeof AdministratorMgmtJobTypesIndexRoute
  '/mgmt/jobs/': typeof AdministratorMgmtJobsIndexRoute
  '/mgmt/staff-directory/': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/mgmt/jobs/folder-templates/': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/mgmt/access-control/roles/$code/': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceWorkbenchRoute
  '/login': typeof AuthenticationLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/notifications': typeof WorkspaceNotificationsRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/schedule': typeof WorkspaceScheduleRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/administrator/more': typeof AdministratorAdministratorMoreRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin': typeof AdministratorAdminIndexRoute
  '/financial': typeof AdministratorFinancialIndexRoute
  '/financial/ledger/$id': typeof AdministratorFinancialLedgerIdRoute
  '/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/mgmt/job-titles/$code': typeof AdministratorMgmtJobTitlesCodeRoute
  '/mgmt/job-types/$id': typeof AdministratorMgmtJobTypesIdRoute
  '/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/mgmt/jobs/create': typeof AdministratorMgmtJobsCreateRoute
  '/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/financial/ledger': typeof AdministratorFinancialLedgerIndexRoute
  '/financial/payouts': typeof AdministratorFinancialPayoutsIndexRoute
  '/mgmt/access-control': typeof AdministratorMgmtAccessControlIndexRoute
  '/mgmt/clients': typeof AdministratorMgmtClientsIndexRoute
  '/mgmt/departments': typeof AdministratorMgmtDepartmentsIndexRoute
  '/mgmt/file-docs': typeof AdministratorMgmtFileDocsIndexRoute
  '/mgmt/job-titles': typeof AdministratorMgmtJobTitlesIndexRoute
  '/mgmt/job-types': typeof AdministratorMgmtJobTypesIndexRoute
  '/mgmt/jobs': typeof AdministratorMgmtJobsIndexRoute
  '/mgmt/staff-directory': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/mgmt/jobs/folder-templates': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/mgmt/access-control/roles/$code': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_administrator': typeof AdministratorRouteWithChildren
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_public/help-center': typeof PublicHelpCenterRoute
  '/_workspace/_workbench': typeof WorkspaceWorkbenchRoute
  '/_workspace/notifications': typeof WorkspaceNotificationsRoute
  '/_workspace/overview': typeof WorkspaceOverviewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/schedule': typeof WorkspaceScheduleRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/': typeof SettingsIndexRoute
  '/_administrator/admin/inbox': typeof AdministratorAdminInboxRoute
  '/_administrator/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/_administrator/admin/settings': typeof AdministratorAdminSettingsRoute
  '/_administrator/administrator/more': typeof AdministratorAdministratorMoreRoute
  '/_administrator/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/_administrator/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/_administrator/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/_administrator/financial/setting': typeof AdministratorFinancialSettingRoute
  '/_administrator/mgmt/access-control': typeof AdministratorMgmtAccessControlRouteWithChildren
  '/_administrator/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/_authentication/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/_workspace/jobs/$no': typeof WorkspaceJobsNoRoute
  '/_workspace/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/_administrator/admin/': typeof AdministratorAdminIndexRoute
  '/_administrator/financial/': typeof AdministratorFinancialIndexRoute
  '/_administrator/financial/ledger/$id': typeof AdministratorFinancialLedgerIdRoute
  '/_administrator/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/_administrator/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/_administrator/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/_administrator/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/_administrator/mgmt/job-titles/$code': typeof AdministratorMgmtJobTitlesCodeRoute
  '/_administrator/mgmt/job-types/$id': typeof AdministratorMgmtJobTypesIdRoute
  '/_administrator/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/_administrator/mgmt/jobs/create': typeof AdministratorMgmtJobsCreateRoute
  '/_administrator/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/_administrator/financial/ledger/': typeof AdministratorFinancialLedgerIndexRoute
  '/_administrator/financial/payouts/': typeof AdministratorFinancialPayoutsIndexRoute
  '/_administrator/mgmt/access-control/': typeof AdministratorMgmtAccessControlIndexRoute
  '/_administrator/mgmt/clients/': typeof AdministratorMgmtClientsIndexRoute
  '/_administrator/mgmt/departments/': typeof AdministratorMgmtDepartmentsIndexRoute
  '/_administrator/mgmt/file-docs/': typeof AdministratorMgmtFileDocsIndexRoute
  '/_administrator/mgmt/job-titles/': typeof AdministratorMgmtJobTitlesIndexRoute
  '/_administrator/mgmt/job-types/': typeof AdministratorMgmtJobTypesIndexRoute
  '/_administrator/mgmt/jobs/': typeof AdministratorMgmtJobsIndexRoute
  '/_administrator/mgmt/staff-directory/': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/_administrator/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/_administrator/mgmt/jobs/folder-templates/': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/_administrator/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/_administrator/mgmt/access-control/roles/$code/': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/help-center'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/schedule'
    | '/settings/appearance'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings/'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/administrator/more'
    | '/financial/invoice-templates'
    | '/financial/payment-channels'
    | '/financial/receivables'
    | '/financial/setting'
    | '/mgmt/access-control'
    | '/mgmt/revenue'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin/'
    | '/financial/'
    | '/financial/ledger/$id'
    | '/financial/payouts/$no'
    | '/mgmt/access-control/permissions'
    | '/mgmt/clients/$code'
    | '/mgmt/departments/$code'
    | '/mgmt/job-titles/$code'
    | '/mgmt/job-types/$id'
    | '/mgmt/jobs/$no'
    | '/mgmt/jobs/create'
    | '/mgmt/staff-directory/$code'
    | '/financial/ledger/'
    | '/financial/payouts/'
    | '/mgmt/access-control/'
    | '/mgmt/clients/'
    | '/mgmt/departments/'
    | '/mgmt/file-docs/'
    | '/mgmt/job-titles/'
    | '/mgmt/job-types/'
    | '/mgmt/jobs/'
    | '/mgmt/staff-directory/'
    | '/mgmt/jobs/folder-templates/$id'
    | '/mgmt/jobs/folder-templates/'
    | '/mgmt/access-control/roles/$code/perm-matrix'
    | '/mgmt/access-control/roles/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/help-center'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/schedule'
    | '/settings/appearance'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/administrator/more'
    | '/financial/invoice-templates'
    | '/financial/payment-channels'
    | '/financial/receivables'
    | '/financial/setting'
    | '/mgmt/revenue'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin'
    | '/financial'
    | '/financial/ledger/$id'
    | '/financial/payouts/$no'
    | '/mgmt/access-control/permissions'
    | '/mgmt/clients/$code'
    | '/mgmt/departments/$code'
    | '/mgmt/job-titles/$code'
    | '/mgmt/job-types/$id'
    | '/mgmt/jobs/$no'
    | '/mgmt/jobs/create'
    | '/mgmt/staff-directory/$code'
    | '/financial/ledger'
    | '/financial/payouts'
    | '/mgmt/access-control'
    | '/mgmt/clients'
    | '/mgmt/departments'
    | '/mgmt/file-docs'
    | '/mgmt/job-titles'
    | '/mgmt/job-types'
    | '/mgmt/jobs'
    | '/mgmt/staff-directory'
    | '/mgmt/jobs/folder-templates/$id'
    | '/mgmt/jobs/folder-templates'
    | '/mgmt/access-control/roles/$code/perm-matrix'
    | '/mgmt/access-control/roles/$code'
  id:
    | '__root__'
    | '/_administrator'
    | '/_authentication'
    | '/_public'
    | '/_workspace'
    | '/settings'
    | '/_authentication/login'
    | '/_public/help-center'
    | '/_workspace/_workbench'
    | '/_workspace/notifications'
    | '/_workspace/overview'
    | '/_workspace/profile'
    | '/_workspace/schedule'
    | '/settings/appearance'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings/'
    | '/_administrator/admin/inbox'
    | '/_administrator/admin/schedule'
    | '/_administrator/admin/settings'
    | '/_administrator/administrator/more'
    | '/_administrator/financial/invoice-templates'
    | '/_administrator/financial/payment-channels'
    | '/_administrator/financial/receivables'
    | '/_administrator/financial/setting'
    | '/_administrator/mgmt/access-control'
    | '/_administrator/mgmt/revenue'
    | '/_authentication/auth/reset-password'
    | '/_workspace/jobs/$no'
    | '/_workspace/project-center/$tab'
    | '/_administrator/admin/'
    | '/_administrator/financial/'
    | '/_administrator/financial/ledger/$id'
    | '/_administrator/financial/payouts/$no'
    | '/_administrator/mgmt/access-control/permissions'
    | '/_administrator/mgmt/clients/$code'
    | '/_administrator/mgmt/departments/$code'
    | '/_administrator/mgmt/job-titles/$code'
    | '/_administrator/mgmt/job-types/$id'
    | '/_administrator/mgmt/jobs/$no'
    | '/_administrator/mgmt/jobs/create'
    | '/_administrator/mgmt/staff-directory/$code'
    | '/_administrator/financial/ledger/'
    | '/_administrator/financial/payouts/'
    | '/_administrator/mgmt/access-control/'
    | '/_administrator/mgmt/clients/'
    | '/_administrator/mgmt/departments/'
    | '/_administrator/mgmt/file-docs/'
    | '/_administrator/mgmt/job-titles/'
    | '/_administrator/mgmt/job-types/'
    | '/_administrator/mgmt/jobs/'
    | '/_administrator/mgmt/staff-directory/'
    | '/_administrator/mgmt/jobs/folder-templates/$id'
    | '/_administrator/mgmt/jobs/folder-templates/'
    | '/_administrator/mgmt/access-control/roles/$code/perm-matrix'
    | '/_administrator/mgmt/access-control/roles/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdministratorRoute: typeof AdministratorRouteWithChildren
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_administrator': {
      id: '/_administrator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/my-profile': {
      id: '/settings/my-profile'
      path: '/my-profile'
      fullPath: '/settings/my-profile'
      preLoaderRoute: typeof SettingsMyProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/login-and-security': {
      id: '/settings/login-and-security'
      path: '/login-and-security'
      fullPath: '/settings/login-and-security'
      preLoaderRoute: typeof SettingsLoginAndSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_workspace/schedule': {
      id: '/_workspace/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof WorkspaceScheduleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/overview': {
      id: '/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/notifications': {
      id: '/_workspace/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof WorkspaceNotificationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/_workbench': {
      id: '/_workspace/_workbench'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceWorkbenchRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/help-center': {
      id: '/_public/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof PublicHelpCenterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_administrator/financial/': {
      id: '/_administrator/financial/'
      path: '/financial'
      fullPath: '/financial/'
      preLoaderRoute: typeof AdministratorFinancialIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/': {
      id: '/_administrator/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdministratorAdminIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_workspace/project-center/$tab': {
      id: '/_workspace/project-center/$tab'
      path: '/project-center/$tab'
      fullPath: '/project-center/$tab'
      preLoaderRoute: typeof WorkspaceProjectCenterTabRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/jobs/$no': {
      id: '/_workspace/jobs/$no'
      path: '/jobs/$no'
      fullPath: '/jobs/$no'
      preLoaderRoute: typeof WorkspaceJobsNoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_authentication/auth/reset-password': {
      id: '/_authentication/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthenticationAuthResetPasswordRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_administrator/mgmt/revenue': {
      id: '/_administrator/mgmt/revenue'
      path: '/mgmt/revenue'
      fullPath: '/mgmt/revenue'
      preLoaderRoute: typeof AdministratorMgmtRevenueRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control': {
      id: '/_administrator/mgmt/access-control'
      path: '/mgmt/access-control'
      fullPath: '/mgmt/access-control'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/setting': {
      id: '/_administrator/financial/setting'
      path: '/financial/setting'
      fullPath: '/financial/setting'
      preLoaderRoute: typeof AdministratorFinancialSettingRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/receivables': {
      id: '/_administrator/financial/receivables'
      path: '/financial/receivables'
      fullPath: '/financial/receivables'
      preLoaderRoute: typeof AdministratorFinancialReceivablesRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/payment-channels': {
      id: '/_administrator/financial/payment-channels'
      path: '/financial/payment-channels'
      fullPath: '/financial/payment-channels'
      preLoaderRoute: typeof AdministratorFinancialPaymentChannelsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/invoice-templates': {
      id: '/_administrator/financial/invoice-templates'
      path: '/financial/invoice-templates'
      fullPath: '/financial/invoice-templates'
      preLoaderRoute: typeof AdministratorFinancialInvoiceTemplatesRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/administrator/more': {
      id: '/_administrator/administrator/more'
      path: '/administrator/more'
      fullPath: '/administrator/more'
      preLoaderRoute: typeof AdministratorAdministratorMoreRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/settings': {
      id: '/_administrator/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdministratorAdminSettingsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/schedule': {
      id: '/_administrator/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdministratorAdminScheduleRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/inbox': {
      id: '/_administrator/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdministratorAdminInboxRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/staff-directory/': {
      id: '/_administrator/mgmt/staff-directory/'
      path: '/mgmt/staff-directory'
      fullPath: '/mgmt/staff-directory/'
      preLoaderRoute: typeof AdministratorMgmtStaffDirectoryIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/': {
      id: '/_administrator/mgmt/jobs/'
      path: '/mgmt/jobs'
      fullPath: '/mgmt/jobs/'
      preLoaderRoute: typeof AdministratorMgmtJobsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/job-types/': {
      id: '/_administrator/mgmt/job-types/'
      path: '/mgmt/job-types'
      fullPath: '/mgmt/job-types/'
      preLoaderRoute: typeof AdministratorMgmtJobTypesIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/job-titles/': {
      id: '/_administrator/mgmt/job-titles/'
      path: '/mgmt/job-titles'
      fullPath: '/mgmt/job-titles/'
      preLoaderRoute: typeof AdministratorMgmtJobTitlesIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/file-docs/': {
      id: '/_administrator/mgmt/file-docs/'
      path: '/mgmt/file-docs'
      fullPath: '/mgmt/file-docs/'
      preLoaderRoute: typeof AdministratorMgmtFileDocsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/departments/': {
      id: '/_administrator/mgmt/departments/'
      path: '/mgmt/departments'
      fullPath: '/mgmt/departments/'
      preLoaderRoute: typeof AdministratorMgmtDepartmentsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/clients/': {
      id: '/_administrator/mgmt/clients/'
      path: '/mgmt/clients'
      fullPath: '/mgmt/clients/'
      preLoaderRoute: typeof AdministratorMgmtClientsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/': {
      id: '/_administrator/mgmt/access-control/'
      path: '/'
      fullPath: '/mgmt/access-control/'
      preLoaderRoute: typeof AdministratorMgmtAccessControlIndexRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/financial/payouts/': {
      id: '/_administrator/financial/payouts/'
      path: '/financial/payouts'
      fullPath: '/financial/payouts/'
      preLoaderRoute: typeof AdministratorFinancialPayoutsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/ledger/': {
      id: '/_administrator/financial/ledger/'
      path: '/financial/ledger'
      fullPath: '/financial/ledger/'
      preLoaderRoute: typeof AdministratorFinancialLedgerIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/staff-directory/$code': {
      id: '/_administrator/mgmt/staff-directory/$code'
      path: '/mgmt/staff-directory/$code'
      fullPath: '/mgmt/staff-directory/$code'
      preLoaderRoute: typeof AdministratorMgmtStaffDirectoryCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/create': {
      id: '/_administrator/mgmt/jobs/create'
      path: '/mgmt/jobs/create'
      fullPath: '/mgmt/jobs/create'
      preLoaderRoute: typeof AdministratorMgmtJobsCreateRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/$no': {
      id: '/_administrator/mgmt/jobs/$no'
      path: '/mgmt/jobs/$no'
      fullPath: '/mgmt/jobs/$no'
      preLoaderRoute: typeof AdministratorMgmtJobsNoRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/job-types/$id': {
      id: '/_administrator/mgmt/job-types/$id'
      path: '/mgmt/job-types/$id'
      fullPath: '/mgmt/job-types/$id'
      preLoaderRoute: typeof AdministratorMgmtJobTypesIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/job-titles/$code': {
      id: '/_administrator/mgmt/job-titles/$code'
      path: '/mgmt/job-titles/$code'
      fullPath: '/mgmt/job-titles/$code'
      preLoaderRoute: typeof AdministratorMgmtJobTitlesCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/departments/$code': {
      id: '/_administrator/mgmt/departments/$code'
      path: '/mgmt/departments/$code'
      fullPath: '/mgmt/departments/$code'
      preLoaderRoute: typeof AdministratorMgmtDepartmentsCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/clients/$code': {
      id: '/_administrator/mgmt/clients/$code'
      path: '/mgmt/clients/$code'
      fullPath: '/mgmt/clients/$code'
      preLoaderRoute: typeof AdministratorMgmtClientsCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/permissions': {
      id: '/_administrator/mgmt/access-control/permissions'
      path: '/permissions'
      fullPath: '/mgmt/access-control/permissions'
      preLoaderRoute: typeof AdministratorMgmtAccessControlPermissionsRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/financial/payouts/$no': {
      id: '/_administrator/financial/payouts/$no'
      path: '/financial/payouts/$no'
      fullPath: '/financial/payouts/$no'
      preLoaderRoute: typeof AdministratorFinancialPayoutsNoRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/ledger/$id': {
      id: '/_administrator/financial/ledger/$id'
      path: '/financial/ledger/$id'
      fullPath: '/financial/ledger/$id'
      preLoaderRoute: typeof AdministratorFinancialLedgerIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/folder-templates/': {
      id: '/_administrator/mgmt/jobs/folder-templates/'
      path: '/mgmt/jobs/folder-templates'
      fullPath: '/mgmt/jobs/folder-templates/'
      preLoaderRoute: typeof AdministratorMgmtJobsFolderTemplatesIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/folder-templates/$id': {
      id: '/_administrator/mgmt/jobs/folder-templates/$id'
      path: '/mgmt/jobs/folder-templates/$id'
      fullPath: '/mgmt/jobs/folder-templates/$id'
      preLoaderRoute: typeof AdministratorMgmtJobsFolderTemplatesIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/roles/$code/': {
      id: '/_administrator/mgmt/access-control/roles/$code/'
      path: '/roles/$code'
      fullPath: '/mgmt/access-control/roles/$code/'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRolesCodeIndexRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/mgmt/access-control/roles/$code/perm-matrix': {
      id: '/_administrator/mgmt/access-control/roles/$code/perm-matrix'
      path: '/roles/$code/perm-matrix'
      fullPath: '/mgmt/access-control/roles/$code/perm-matrix'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
  }
}

interface AdministratorMgmtAccessControlRouteChildren {
  AdministratorMgmtAccessControlPermissionsRoute: typeof AdministratorMgmtAccessControlPermissionsRoute
  AdministratorMgmtAccessControlIndexRoute: typeof AdministratorMgmtAccessControlIndexRoute
  AdministratorMgmtAccessControlRolesCodePermMatrixRoute: typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  AdministratorMgmtAccessControlRolesCodeIndexRoute: typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}

const AdministratorMgmtAccessControlRouteChildren: AdministratorMgmtAccessControlRouteChildren =
  {
    AdministratorMgmtAccessControlPermissionsRoute:
      AdministratorMgmtAccessControlPermissionsRoute,
    AdministratorMgmtAccessControlIndexRoute:
      AdministratorMgmtAccessControlIndexRoute,
    AdministratorMgmtAccessControlRolesCodePermMatrixRoute:
      AdministratorMgmtAccessControlRolesCodePermMatrixRoute,
    AdministratorMgmtAccessControlRolesCodeIndexRoute:
      AdministratorMgmtAccessControlRolesCodeIndexRoute,
  }

const AdministratorMgmtAccessControlRouteWithChildren =
  AdministratorMgmtAccessControlRoute._addFileChildren(
    AdministratorMgmtAccessControlRouteChildren,
  )

interface AdministratorRouteChildren {
  AdministratorAdminInboxRoute: typeof AdministratorAdminInboxRoute
  AdministratorAdminScheduleRoute: typeof AdministratorAdminScheduleRoute
  AdministratorAdminSettingsRoute: typeof AdministratorAdminSettingsRoute
  AdministratorAdministratorMoreRoute: typeof AdministratorAdministratorMoreRoute
  AdministratorFinancialInvoiceTemplatesRoute: typeof AdministratorFinancialInvoiceTemplatesRoute
  AdministratorFinancialPaymentChannelsRoute: typeof AdministratorFinancialPaymentChannelsRoute
  AdministratorFinancialReceivablesRoute: typeof AdministratorFinancialReceivablesRoute
  AdministratorFinancialSettingRoute: typeof AdministratorFinancialSettingRoute
  AdministratorMgmtAccessControlRoute: typeof AdministratorMgmtAccessControlRouteWithChildren
  AdministratorMgmtRevenueRoute: typeof AdministratorMgmtRevenueRoute
  AdministratorAdminIndexRoute: typeof AdministratorAdminIndexRoute
  AdministratorFinancialIndexRoute: typeof AdministratorFinancialIndexRoute
  AdministratorFinancialLedgerIdRoute: typeof AdministratorFinancialLedgerIdRoute
  AdministratorFinancialPayoutsNoRoute: typeof AdministratorFinancialPayoutsNoRoute
  AdministratorMgmtClientsCodeRoute: typeof AdministratorMgmtClientsCodeRoute
  AdministratorMgmtDepartmentsCodeRoute: typeof AdministratorMgmtDepartmentsCodeRoute
  AdministratorMgmtJobTitlesCodeRoute: typeof AdministratorMgmtJobTitlesCodeRoute
  AdministratorMgmtJobTypesIdRoute: typeof AdministratorMgmtJobTypesIdRoute
  AdministratorMgmtJobsNoRoute: typeof AdministratorMgmtJobsNoRoute
  AdministratorMgmtJobsCreateRoute: typeof AdministratorMgmtJobsCreateRoute
  AdministratorMgmtStaffDirectoryCodeRoute: typeof AdministratorMgmtStaffDirectoryCodeRoute
  AdministratorFinancialLedgerIndexRoute: typeof AdministratorFinancialLedgerIndexRoute
  AdministratorFinancialPayoutsIndexRoute: typeof AdministratorFinancialPayoutsIndexRoute
  AdministratorMgmtClientsIndexRoute: typeof AdministratorMgmtClientsIndexRoute
  AdministratorMgmtDepartmentsIndexRoute: typeof AdministratorMgmtDepartmentsIndexRoute
  AdministratorMgmtFileDocsIndexRoute: typeof AdministratorMgmtFileDocsIndexRoute
  AdministratorMgmtJobTitlesIndexRoute: typeof AdministratorMgmtJobTitlesIndexRoute
  AdministratorMgmtJobTypesIndexRoute: typeof AdministratorMgmtJobTypesIndexRoute
  AdministratorMgmtJobsIndexRoute: typeof AdministratorMgmtJobsIndexRoute
  AdministratorMgmtStaffDirectoryIndexRoute: typeof AdministratorMgmtStaffDirectoryIndexRoute
  AdministratorMgmtJobsFolderTemplatesIdRoute: typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  AdministratorMgmtJobsFolderTemplatesIndexRoute: typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
}

const AdministratorRouteChildren: AdministratorRouteChildren = {
  AdministratorAdminInboxRoute: AdministratorAdminInboxRoute,
  AdministratorAdminScheduleRoute: AdministratorAdminScheduleRoute,
  AdministratorAdminSettingsRoute: AdministratorAdminSettingsRoute,
  AdministratorAdministratorMoreRoute: AdministratorAdministratorMoreRoute,
  AdministratorFinancialInvoiceTemplatesRoute:
    AdministratorFinancialInvoiceTemplatesRoute,
  AdministratorFinancialPaymentChannelsRoute:
    AdministratorFinancialPaymentChannelsRoute,
  AdministratorFinancialReceivablesRoute:
    AdministratorFinancialReceivablesRoute,
  AdministratorFinancialSettingRoute: AdministratorFinancialSettingRoute,
  AdministratorMgmtAccessControlRoute:
    AdministratorMgmtAccessControlRouteWithChildren,
  AdministratorMgmtRevenueRoute: AdministratorMgmtRevenueRoute,
  AdministratorAdminIndexRoute: AdministratorAdminIndexRoute,
  AdministratorFinancialIndexRoute: AdministratorFinancialIndexRoute,
  AdministratorFinancialLedgerIdRoute: AdministratorFinancialLedgerIdRoute,
  AdministratorFinancialPayoutsNoRoute: AdministratorFinancialPayoutsNoRoute,
  AdministratorMgmtClientsCodeRoute: AdministratorMgmtClientsCodeRoute,
  AdministratorMgmtDepartmentsCodeRoute: AdministratorMgmtDepartmentsCodeRoute,
  AdministratorMgmtJobTitlesCodeRoute: AdministratorMgmtJobTitlesCodeRoute,
  AdministratorMgmtJobTypesIdRoute: AdministratorMgmtJobTypesIdRoute,
  AdministratorMgmtJobsNoRoute: AdministratorMgmtJobsNoRoute,
  AdministratorMgmtJobsCreateRoute: AdministratorMgmtJobsCreateRoute,
  AdministratorMgmtStaffDirectoryCodeRoute:
    AdministratorMgmtStaffDirectoryCodeRoute,
  AdministratorFinancialLedgerIndexRoute:
    AdministratorFinancialLedgerIndexRoute,
  AdministratorFinancialPayoutsIndexRoute:
    AdministratorFinancialPayoutsIndexRoute,
  AdministratorMgmtClientsIndexRoute: AdministratorMgmtClientsIndexRoute,
  AdministratorMgmtDepartmentsIndexRoute:
    AdministratorMgmtDepartmentsIndexRoute,
  AdministratorMgmtFileDocsIndexRoute: AdministratorMgmtFileDocsIndexRoute,
  AdministratorMgmtJobTitlesIndexRoute: AdministratorMgmtJobTitlesIndexRoute,
  AdministratorMgmtJobTypesIndexRoute: AdministratorMgmtJobTypesIndexRoute,
  AdministratorMgmtJobsIndexRoute: AdministratorMgmtJobsIndexRoute,
  AdministratorMgmtStaffDirectoryIndexRoute:
    AdministratorMgmtStaffDirectoryIndexRoute,
  AdministratorMgmtJobsFolderTemplatesIdRoute:
    AdministratorMgmtJobsFolderTemplatesIdRoute,
  AdministratorMgmtJobsFolderTemplatesIndexRoute:
    AdministratorMgmtJobsFolderTemplatesIndexRoute,
}

const AdministratorRouteWithChildren = AdministratorRoute._addFileChildren(
  AdministratorRouteChildren,
)

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationAuthResetPasswordRoute: typeof AuthenticationAuthResetPasswordRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationAuthResetPasswordRoute: AuthenticationAuthResetPasswordRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

interface PublicRouteChildren {
  PublicHelpCenterRoute: typeof PublicHelpCenterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHelpCenterRoute: PublicHelpCenterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceWorkbenchRoute: typeof WorkspaceWorkbenchRoute
  WorkspaceNotificationsRoute: typeof WorkspaceNotificationsRoute
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceScheduleRoute: typeof WorkspaceScheduleRoute
  WorkspaceJobsNoRoute: typeof WorkspaceJobsNoRoute
  WorkspaceProjectCenterTabRoute: typeof WorkspaceProjectCenterTabRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkbenchRoute: WorkspaceWorkbenchRoute,
  WorkspaceNotificationsRoute: WorkspaceNotificationsRoute,
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceScheduleRoute: WorkspaceScheduleRoute,
  WorkspaceJobsNoRoute: WorkspaceJobsNoRoute,
  WorkspaceProjectCenterTabRoute: WorkspaceProjectCenterTabRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLoginAndSecurityRoute: typeof SettingsLoginAndSecurityRoute
  SettingsMyProfileRoute: typeof SettingsMyProfileRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLoginAndSecurityRoute: SettingsLoginAndSecurityRoute,
  SettingsMyProfileRoute: SettingsMyProfileRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdministratorRoute: AdministratorRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
