/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdministratorRouteImport } from './routes/_administrator'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsMyProfileRouteImport } from './routes/settings/my-profile'
import { Route as SettingsLoginAndSecurityRouteImport } from './routes/settings/login-and-security'
import { Route as SettingsLanguageAndRegionRouteImport } from './routes/settings/language-and-region'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as WorkspaceTaskSummaryRouteImport } from './routes/_workspace/task-summary'
import { Route as WorkspaceScheduleRouteImport } from './routes/_workspace/schedule'
import { Route as WorkspaceProjectCenterRouteImport } from './routes/_workspace/project-center'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace/profile'
import { Route as WorkspaceOverviewRouteImport } from './routes/_workspace/overview'
import { Route as PublicHelpCenterRouteImport } from './routes/_public/help-center'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as WorkspaceProjectCenterIndexRouteImport } from './routes/_workspace/project-center/index'
import { Route as WorkspaceNotificationsIndexRouteImport } from './routes/_workspace/notifications/index'
import { Route as WorkspaceJobsIndexRouteImport } from './routes/_workspace/jobs/index'
import { Route as WorkspaceWorkbenchIndexRouteImport } from './routes/_workspace/_workbench/index'
import { Route as AdministratorFinancialIndexRouteImport } from './routes/_administrator/financial/index'
import { Route as AdministratorAdminIndexRouteImport } from './routes/_administrator/admin/index'
import { Route as WorkspaceProjectCenterTabRouteImport } from './routes/_workspace/project-center/$tab'
import { Route as WorkspaceJobsNoRouteImport } from './routes/_workspace/jobs/$no'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth/reset-password'
import { Route as AdministratorMgmtRevenueRouteImport } from './routes/_administrator/mgmt/revenue'
import { Route as AdministratorMgmtInviteMemberRouteImport } from './routes/_administrator/mgmt/invite-member'
import { Route as AdministratorMgmtAccessControlRouteImport } from './routes/_administrator/mgmt/access-control'
import { Route as AdministratorFinancialSettingRouteImport } from './routes/_administrator/financial/setting'
import { Route as AdministratorFinancialReceivablesRouteImport } from './routes/_administrator/financial/receivables'
import { Route as AdministratorFinancialPaymentChannelsRouteImport } from './routes/_administrator/financial/payment-channels'
import { Route as AdministratorFinancialLedgerRouteImport } from './routes/_administrator/financial/ledger'
import { Route as AdministratorFinancialInvoiceTemplatesRouteImport } from './routes/_administrator/financial/invoice-templates'
import { Route as AdministratorAdminSettingsRouteImport } from './routes/_administrator/admin/settings'
import { Route as AdministratorAdminScheduleRouteImport } from './routes/_administrator/admin/schedule'
import { Route as AdministratorAdminInboxRouteImport } from './routes/_administrator/admin/inbox'
import { Route as AdministratorMgmtStaffDirectoryIndexRouteImport } from './routes/_administrator/mgmt/staff-directory/index'
import { Route as AdministratorMgmtJobsIndexRouteImport } from './routes/_administrator/mgmt/jobs/index'
import { Route as AdministratorMgmtFileDocsIndexRouteImport } from './routes/_administrator/mgmt/file-docs/index'
import { Route as AdministratorMgmtDepartmentsIndexRouteImport } from './routes/_administrator/mgmt/departments/index'
import { Route as AdministratorMgmtClientsIndexRouteImport } from './routes/_administrator/mgmt/clients/index'
import { Route as AdministratorMgmtAccessControlIndexRouteImport } from './routes/_administrator/mgmt/access-control/index'
import { Route as AdministratorFinancialPayoutsIndexRouteImport } from './routes/_administrator/financial/payouts/index'
import { Route as AdministratorMgmtStaffDirectoryCodeRouteImport } from './routes/_administrator/mgmt/staff-directory/$code'
import { Route as AdministratorMgmtJobsNoRouteImport } from './routes/_administrator/mgmt/jobs/$no'
import { Route as AdministratorMgmtDepartmentsCodeRouteImport } from './routes/_administrator/mgmt/departments/$code'
import { Route as AdministratorMgmtClientsCodeRouteImport } from './routes/_administrator/mgmt/clients/$code'
import { Route as AdministratorMgmtAccessControlPermissionsRouteImport } from './routes/_administrator/mgmt/access-control/permissions'
import { Route as AdministratorMgmtAccessControlMatrixRouteImport } from './routes/_administrator/mgmt/access-control/matrix'
import { Route as AdministratorFinancialPayoutsNoRouteImport } from './routes/_administrator/financial/payouts/$no'
import { Route as AdministratorMgmtJobsFolderTemplatesIndexRouteImport } from './routes/_administrator/mgmt/jobs/folder-templates/index'
import { Route as AdministratorMgmtAccessControlUsersIndexRouteImport } from './routes/_administrator/mgmt/access-control/users/index'
import { Route as AdministratorMgmtJobsFolderTemplatesIdRouteImport } from './routes/_administrator/mgmt/jobs/folder-templates/$id'
import { Route as AdministratorMgmtAccessControlUsersUsernameRouteImport } from './routes/_administrator/mgmt/access-control/users/$username'
import { Route as AdministratorMgmtAccessControlRolesCodeIndexRouteImport } from './routes/_administrator/mgmt/access-control/roles/$code/index'
import { Route as AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport } from './routes/_administrator/mgmt/access-control/roles/$code/perm-matrix'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/_administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMyProfileRoute = SettingsMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLoginAndSecurityRoute =
  SettingsLoginAndSecurityRouteImport.update({
    id: '/login-and-security',
    path: '/login-and-security',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsLanguageAndRegionRoute =
  SettingsLanguageAndRegionRouteImport.update({
    id: '/language-and-region',
    path: '/language-and-region',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkspaceTaskSummaryRoute = WorkspaceTaskSummaryRouteImport.update({
  id: '/task-summary',
  path: '/task-summary',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceScheduleRoute = WorkspaceScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectCenterRoute = WorkspaceProjectCenterRouteImport.update({
  id: '/project-center',
  path: '/project-center',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOverviewRoute = WorkspaceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PublicHelpCenterRoute = PublicHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => PublicRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const WorkspaceProjectCenterIndexRoute =
  WorkspaceProjectCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectCenterRoute,
  } as any)
const WorkspaceNotificationsIndexRoute =
  WorkspaceNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceJobsIndexRoute = WorkspaceJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkbenchIndexRoute = WorkspaceWorkbenchIndexRouteImport.update({
  id: '/_workbench/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AdministratorFinancialIndexRoute =
  AdministratorFinancialIndexRouteImport.update({
    id: '/financial/',
    path: '/financial/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminIndexRoute = AdministratorAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdministratorRoute,
} as any)
const WorkspaceProjectCenterTabRoute =
  WorkspaceProjectCenterTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => WorkspaceProjectCenterRoute,
  } as any)
const WorkspaceJobsNoRoute = WorkspaceJobsNoRouteImport.update({
  id: '/jobs/$no',
  path: '/jobs/$no',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdministratorMgmtRevenueRoute =
  AdministratorMgmtRevenueRouteImport.update({
    id: '/mgmt/revenue',
    path: '/mgmt/revenue',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtInviteMemberRoute =
  AdministratorMgmtInviteMemberRouteImport.update({
    id: '/mgmt/invite-member',
    path: '/mgmt/invite-member',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlRoute =
  AdministratorMgmtAccessControlRouteImport.update({
    id: '/mgmt/access-control',
    path: '/mgmt/access-control',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialSettingRoute =
  AdministratorFinancialSettingRouteImport.update({
    id: '/financial/setting',
    path: '/financial/setting',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialReceivablesRoute =
  AdministratorFinancialReceivablesRouteImport.update({
    id: '/financial/receivables',
    path: '/financial/receivables',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialPaymentChannelsRoute =
  AdministratorFinancialPaymentChannelsRouteImport.update({
    id: '/financial/payment-channels',
    path: '/financial/payment-channels',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialLedgerRoute =
  AdministratorFinancialLedgerRouteImport.update({
    id: '/financial/ledger',
    path: '/financial/ledger',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFinancialInvoiceTemplatesRoute =
  AdministratorFinancialInvoiceTemplatesRouteImport.update({
    id: '/financial/invoice-templates',
    path: '/financial/invoice-templates',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminSettingsRoute =
  AdministratorAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminScheduleRoute =
  AdministratorAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorAdminInboxRoute = AdministratorAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMgmtStaffDirectoryIndexRoute =
  AdministratorMgmtStaffDirectoryIndexRouteImport.update({
    id: '/mgmt/staff-directory/',
    path: '/mgmt/staff-directory/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsIndexRoute =
  AdministratorMgmtJobsIndexRouteImport.update({
    id: '/mgmt/jobs/',
    path: '/mgmt/jobs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtFileDocsIndexRoute =
  AdministratorMgmtFileDocsIndexRouteImport.update({
    id: '/mgmt/file-docs/',
    path: '/mgmt/file-docs/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtDepartmentsIndexRoute =
  AdministratorMgmtDepartmentsIndexRouteImport.update({
    id: '/mgmt/departments/',
    path: '/mgmt/departments/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtClientsIndexRoute =
  AdministratorMgmtClientsIndexRouteImport.update({
    id: '/mgmt/clients/',
    path: '/mgmt/clients/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlIndexRoute =
  AdministratorMgmtAccessControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorFinancialPayoutsIndexRoute =
  AdministratorFinancialPayoutsIndexRouteImport.update({
    id: '/financial/payouts/',
    path: '/financial/payouts/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtStaffDirectoryCodeRoute =
  AdministratorMgmtStaffDirectoryCodeRouteImport.update({
    id: '/mgmt/staff-directory/$code',
    path: '/mgmt/staff-directory/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsNoRoute = AdministratorMgmtJobsNoRouteImport.update({
  id: '/mgmt/jobs/$no',
  path: '/mgmt/jobs/$no',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMgmtDepartmentsCodeRoute =
  AdministratorMgmtDepartmentsCodeRouteImport.update({
    id: '/mgmt/departments/$code',
    path: '/mgmt/departments/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtClientsCodeRoute =
  AdministratorMgmtClientsCodeRouteImport.update({
    id: '/mgmt/clients/$code',
    path: '/mgmt/clients/$code',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlPermissionsRoute =
  AdministratorMgmtAccessControlPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorMgmtAccessControlMatrixRoute =
  AdministratorMgmtAccessControlMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorFinancialPayoutsNoRoute =
  AdministratorFinancialPayoutsNoRouteImport.update({
    id: '/financial/payouts/$no',
    path: '/financial/payouts/$no',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtJobsFolderTemplatesIndexRoute =
  AdministratorMgmtJobsFolderTemplatesIndexRouteImport.update({
    id: '/mgmt/jobs/folder-templates/',
    path: '/mgmt/jobs/folder-templates/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlUsersIndexRoute =
  AdministratorMgmtAccessControlUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorMgmtJobsFolderTemplatesIdRoute =
  AdministratorMgmtJobsFolderTemplatesIdRouteImport.update({
    id: '/mgmt/jobs/folder-templates/$id',
    path: '/mgmt/jobs/folder-templates/$id',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorMgmtAccessControlUsersUsernameRoute =
  AdministratorMgmtAccessControlUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorMgmtAccessControlRolesCodeIndexRoute =
  AdministratorMgmtAccessControlRolesCodeIndexRouteImport.update({
    id: '/roles/$code/',
    path: '/roles/$code/',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)
const AdministratorMgmtAccessControlRolesCodePermMatrixRoute =
  AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport.update({
    id: '/roles/$code/perm-matrix',
    path: '/roles/$code/perm-matrix',
    getParentRoute: () => AdministratorMgmtAccessControlRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceWorkbenchIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/project-center': typeof WorkspaceProjectCenterRouteWithChildren
  '/schedule': typeof WorkspaceScheduleRoute
  '/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/ledger': typeof AdministratorFinancialLedgerRoute
  '/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/mgmt/access-control': typeof AdministratorMgmtAccessControlRouteWithChildren
  '/mgmt/invite-member': typeof AdministratorMgmtInviteMemberRoute
  '/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin/': typeof AdministratorAdminIndexRoute
  '/financial/': typeof AdministratorFinancialIndexRoute
  '/jobs/': typeof WorkspaceJobsIndexRoute
  '/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/project-center/': typeof WorkspaceProjectCenterIndexRoute
  '/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/mgmt/access-control/matrix': typeof AdministratorMgmtAccessControlMatrixRoute
  '/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/financial/payouts/': typeof AdministratorFinancialPayoutsIndexRoute
  '/mgmt/access-control/': typeof AdministratorMgmtAccessControlIndexRoute
  '/mgmt/clients/': typeof AdministratorMgmtClientsIndexRoute
  '/mgmt/departments/': typeof AdministratorMgmtDepartmentsIndexRoute
  '/mgmt/file-docs/': typeof AdministratorMgmtFileDocsIndexRoute
  '/mgmt/jobs/': typeof AdministratorMgmtJobsIndexRoute
  '/mgmt/staff-directory/': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/mgmt/access-control/users/$username': typeof AdministratorMgmtAccessControlUsersUsernameRoute
  '/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/mgmt/access-control/users/': typeof AdministratorMgmtAccessControlUsersIndexRoute
  '/mgmt/jobs/folder-templates/': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/mgmt/access-control/roles/$code/': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceWorkbenchIndexRoute
  '/login': typeof AuthLoginRoute
  '/help-center': typeof PublicHelpCenterRoute
  '/overview': typeof WorkspaceOverviewRoute
  '/profile': typeof WorkspaceProfileRoute
  '/schedule': typeof WorkspaceScheduleRoute
  '/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/inbox': typeof AdministratorAdminInboxRoute
  '/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/admin/settings': typeof AdministratorAdminSettingsRoute
  '/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/financial/ledger': typeof AdministratorFinancialLedgerRoute
  '/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/financial/setting': typeof AdministratorFinancialSettingRoute
  '/mgmt/invite-member': typeof AdministratorMgmtInviteMemberRoute
  '/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/jobs/$no': typeof WorkspaceJobsNoRoute
  '/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/admin': typeof AdministratorAdminIndexRoute
  '/financial': typeof AdministratorFinancialIndexRoute
  '/jobs': typeof WorkspaceJobsIndexRoute
  '/notifications': typeof WorkspaceNotificationsIndexRoute
  '/project-center': typeof WorkspaceProjectCenterIndexRoute
  '/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/mgmt/access-control/matrix': typeof AdministratorMgmtAccessControlMatrixRoute
  '/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/financial/payouts': typeof AdministratorFinancialPayoutsIndexRoute
  '/mgmt/access-control': typeof AdministratorMgmtAccessControlIndexRoute
  '/mgmt/clients': typeof AdministratorMgmtClientsIndexRoute
  '/mgmt/departments': typeof AdministratorMgmtDepartmentsIndexRoute
  '/mgmt/file-docs': typeof AdministratorMgmtFileDocsIndexRoute
  '/mgmt/jobs': typeof AdministratorMgmtJobsIndexRoute
  '/mgmt/staff-directory': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/mgmt/access-control/users/$username': typeof AdministratorMgmtAccessControlUsersUsernameRoute
  '/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/mgmt/access-control/users': typeof AdministratorMgmtAccessControlUsersIndexRoute
  '/mgmt/jobs/folder-templates': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/mgmt/access-control/roles/$code': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_administrator': typeof AdministratorRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_public/help-center': typeof PublicHelpCenterRoute
  '/_workspace/overview': typeof WorkspaceOverviewRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/project-center': typeof WorkspaceProjectCenterRouteWithChildren
  '/_workspace/schedule': typeof WorkspaceScheduleRoute
  '/_workspace/task-summary': typeof WorkspaceTaskSummaryRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language-and-region': typeof SettingsLanguageAndRegionRoute
  '/settings/login-and-security': typeof SettingsLoginAndSecurityRoute
  '/settings/my-profile': typeof SettingsMyProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/': typeof SettingsIndexRoute
  '/_administrator/admin/inbox': typeof AdministratorAdminInboxRoute
  '/_administrator/admin/schedule': typeof AdministratorAdminScheduleRoute
  '/_administrator/admin/settings': typeof AdministratorAdminSettingsRoute
  '/_administrator/financial/invoice-templates': typeof AdministratorFinancialInvoiceTemplatesRoute
  '/_administrator/financial/ledger': typeof AdministratorFinancialLedgerRoute
  '/_administrator/financial/payment-channels': typeof AdministratorFinancialPaymentChannelsRoute
  '/_administrator/financial/receivables': typeof AdministratorFinancialReceivablesRoute
  '/_administrator/financial/setting': typeof AdministratorFinancialSettingRoute
  '/_administrator/mgmt/access-control': typeof AdministratorMgmtAccessControlRouteWithChildren
  '/_administrator/mgmt/invite-member': typeof AdministratorMgmtInviteMemberRoute
  '/_administrator/mgmt/revenue': typeof AdministratorMgmtRevenueRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/_workspace/jobs/$no': typeof WorkspaceJobsNoRoute
  '/_workspace/project-center/$tab': typeof WorkspaceProjectCenterTabRoute
  '/_administrator/admin/': typeof AdministratorAdminIndexRoute
  '/_administrator/financial/': typeof AdministratorFinancialIndexRoute
  '/_workspace/_workbench/': typeof WorkspaceWorkbenchIndexRoute
  '/_workspace/jobs/': typeof WorkspaceJobsIndexRoute
  '/_workspace/notifications/': typeof WorkspaceNotificationsIndexRoute
  '/_workspace/project-center/': typeof WorkspaceProjectCenterIndexRoute
  '/_administrator/financial/payouts/$no': typeof AdministratorFinancialPayoutsNoRoute
  '/_administrator/mgmt/access-control/matrix': typeof AdministratorMgmtAccessControlMatrixRoute
  '/_administrator/mgmt/access-control/permissions': typeof AdministratorMgmtAccessControlPermissionsRoute
  '/_administrator/mgmt/clients/$code': typeof AdministratorMgmtClientsCodeRoute
  '/_administrator/mgmt/departments/$code': typeof AdministratorMgmtDepartmentsCodeRoute
  '/_administrator/mgmt/jobs/$no': typeof AdministratorMgmtJobsNoRoute
  '/_administrator/mgmt/staff-directory/$code': typeof AdministratorMgmtStaffDirectoryCodeRoute
  '/_administrator/financial/payouts/': typeof AdministratorFinancialPayoutsIndexRoute
  '/_administrator/mgmt/access-control/': typeof AdministratorMgmtAccessControlIndexRoute
  '/_administrator/mgmt/clients/': typeof AdministratorMgmtClientsIndexRoute
  '/_administrator/mgmt/departments/': typeof AdministratorMgmtDepartmentsIndexRoute
  '/_administrator/mgmt/file-docs/': typeof AdministratorMgmtFileDocsIndexRoute
  '/_administrator/mgmt/jobs/': typeof AdministratorMgmtJobsIndexRoute
  '/_administrator/mgmt/staff-directory/': typeof AdministratorMgmtStaffDirectoryIndexRoute
  '/_administrator/mgmt/access-control/users/$username': typeof AdministratorMgmtAccessControlUsersUsernameRoute
  '/_administrator/mgmt/jobs/folder-templates/$id': typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  '/_administrator/mgmt/access-control/users/': typeof AdministratorMgmtAccessControlUsersIndexRoute
  '/_administrator/mgmt/jobs/folder-templates/': typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
  '/_administrator/mgmt/access-control/roles/$code/perm-matrix': typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  '/_administrator/mgmt/access-control/roles/$code/': typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/help-center'
    | '/overview'
    | '/profile'
    | '/project-center'
    | '/schedule'
    | '/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings/'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/financial/invoice-templates'
    | '/financial/ledger'
    | '/financial/payment-channels'
    | '/financial/receivables'
    | '/financial/setting'
    | '/mgmt/access-control'
    | '/mgmt/invite-member'
    | '/mgmt/revenue'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin/'
    | '/financial/'
    | '/jobs/'
    | '/notifications/'
    | '/project-center/'
    | '/financial/payouts/$no'
    | '/mgmt/access-control/matrix'
    | '/mgmt/access-control/permissions'
    | '/mgmt/clients/$code'
    | '/mgmt/departments/$code'
    | '/mgmt/jobs/$no'
    | '/mgmt/staff-directory/$code'
    | '/financial/payouts/'
    | '/mgmt/access-control/'
    | '/mgmt/clients/'
    | '/mgmt/departments/'
    | '/mgmt/file-docs/'
    | '/mgmt/jobs/'
    | '/mgmt/staff-directory/'
    | '/mgmt/access-control/users/$username'
    | '/mgmt/jobs/folder-templates/$id'
    | '/mgmt/access-control/users/'
    | '/mgmt/jobs/folder-templates/'
    | '/mgmt/access-control/roles/$code/perm-matrix'
    | '/mgmt/access-control/roles/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/help-center'
    | '/overview'
    | '/profile'
    | '/schedule'
    | '/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings'
    | '/admin/inbox'
    | '/admin/schedule'
    | '/admin/settings'
    | '/financial/invoice-templates'
    | '/financial/ledger'
    | '/financial/payment-channels'
    | '/financial/receivables'
    | '/financial/setting'
    | '/mgmt/invite-member'
    | '/mgmt/revenue'
    | '/auth/reset-password'
    | '/jobs/$no'
    | '/project-center/$tab'
    | '/admin'
    | '/financial'
    | '/jobs'
    | '/notifications'
    | '/project-center'
    | '/financial/payouts/$no'
    | '/mgmt/access-control/matrix'
    | '/mgmt/access-control/permissions'
    | '/mgmt/clients/$code'
    | '/mgmt/departments/$code'
    | '/mgmt/jobs/$no'
    | '/mgmt/staff-directory/$code'
    | '/financial/payouts'
    | '/mgmt/access-control'
    | '/mgmt/clients'
    | '/mgmt/departments'
    | '/mgmt/file-docs'
    | '/mgmt/jobs'
    | '/mgmt/staff-directory'
    | '/mgmt/access-control/users/$username'
    | '/mgmt/jobs/folder-templates/$id'
    | '/mgmt/access-control/users'
    | '/mgmt/jobs/folder-templates'
    | '/mgmt/access-control/roles/$code/perm-matrix'
    | '/mgmt/access-control/roles/$code'
  id:
    | '__root__'
    | '/_administrator'
    | '/_auth'
    | '/_public'
    | '/_workspace'
    | '/settings'
    | '/_auth/login'
    | '/_public/help-center'
    | '/_workspace/overview'
    | '/_workspace/profile'
    | '/_workspace/project-center'
    | '/_workspace/schedule'
    | '/_workspace/task-summary'
    | '/settings/appearance'
    | '/settings/language-and-region'
    | '/settings/login-and-security'
    | '/settings/my-profile'
    | '/settings/notifications'
    | '/settings/'
    | '/_administrator/admin/inbox'
    | '/_administrator/admin/schedule'
    | '/_administrator/admin/settings'
    | '/_administrator/financial/invoice-templates'
    | '/_administrator/financial/ledger'
    | '/_administrator/financial/payment-channels'
    | '/_administrator/financial/receivables'
    | '/_administrator/financial/setting'
    | '/_administrator/mgmt/access-control'
    | '/_administrator/mgmt/invite-member'
    | '/_administrator/mgmt/revenue'
    | '/_auth/auth/reset-password'
    | '/_workspace/jobs/$no'
    | '/_workspace/project-center/$tab'
    | '/_administrator/admin/'
    | '/_administrator/financial/'
    | '/_workspace/_workbench/'
    | '/_workspace/jobs/'
    | '/_workspace/notifications/'
    | '/_workspace/project-center/'
    | '/_administrator/financial/payouts/$no'
    | '/_administrator/mgmt/access-control/matrix'
    | '/_administrator/mgmt/access-control/permissions'
    | '/_administrator/mgmt/clients/$code'
    | '/_administrator/mgmt/departments/$code'
    | '/_administrator/mgmt/jobs/$no'
    | '/_administrator/mgmt/staff-directory/$code'
    | '/_administrator/financial/payouts/'
    | '/_administrator/mgmt/access-control/'
    | '/_administrator/mgmt/clients/'
    | '/_administrator/mgmt/departments/'
    | '/_administrator/mgmt/file-docs/'
    | '/_administrator/mgmt/jobs/'
    | '/_administrator/mgmt/staff-directory/'
    | '/_administrator/mgmt/access-control/users/$username'
    | '/_administrator/mgmt/jobs/folder-templates/$id'
    | '/_administrator/mgmt/access-control/users/'
    | '/_administrator/mgmt/jobs/folder-templates/'
    | '/_administrator/mgmt/access-control/roles/$code/perm-matrix'
    | '/_administrator/mgmt/access-control/roles/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdministratorRoute: typeof AdministratorRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_administrator': {
      id: '/_administrator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/my-profile': {
      id: '/settings/my-profile'
      path: '/my-profile'
      fullPath: '/settings/my-profile'
      preLoaderRoute: typeof SettingsMyProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/login-and-security': {
      id: '/settings/login-and-security'
      path: '/login-and-security'
      fullPath: '/settings/login-and-security'
      preLoaderRoute: typeof SettingsLoginAndSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language-and-region': {
      id: '/settings/language-and-region'
      path: '/language-and-region'
      fullPath: '/settings/language-and-region'
      preLoaderRoute: typeof SettingsLanguageAndRegionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_workspace/task-summary': {
      id: '/_workspace/task-summary'
      path: '/task-summary'
      fullPath: '/task-summary'
      preLoaderRoute: typeof WorkspaceTaskSummaryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/schedule': {
      id: '/_workspace/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof WorkspaceScheduleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/project-center': {
      id: '/_workspace/project-center'
      path: '/project-center'
      fullPath: '/project-center'
      preLoaderRoute: typeof WorkspaceProjectCenterRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/overview': {
      id: '/_workspace/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof WorkspaceOverviewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_public/help-center': {
      id: '/_public/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof PublicHelpCenterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_workspace/project-center/': {
      id: '/_workspace/project-center/'
      path: '/'
      fullPath: '/project-center/'
      preLoaderRoute: typeof WorkspaceProjectCenterIndexRouteImport
      parentRoute: typeof WorkspaceProjectCenterRoute
    }
    '/_workspace/notifications/': {
      id: '/_workspace/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof WorkspaceNotificationsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/jobs/': {
      id: '/_workspace/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof WorkspaceJobsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/_workbench/': {
      id: '/_workspace/_workbench/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceWorkbenchIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_administrator/financial/': {
      id: '/_administrator/financial/'
      path: '/financial'
      fullPath: '/financial/'
      preLoaderRoute: typeof AdministratorFinancialIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/': {
      id: '/_administrator/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdministratorAdminIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_workspace/project-center/$tab': {
      id: '/_workspace/project-center/$tab'
      path: '/$tab'
      fullPath: '/project-center/$tab'
      preLoaderRoute: typeof WorkspaceProjectCenterTabRouteImport
      parentRoute: typeof WorkspaceProjectCenterRoute
    }
    '/_workspace/jobs/$no': {
      id: '/_workspace/jobs/$no'
      path: '/jobs/$no'
      fullPath: '/jobs/$no'
      preLoaderRoute: typeof WorkspaceJobsNoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_administrator/mgmt/revenue': {
      id: '/_administrator/mgmt/revenue'
      path: '/mgmt/revenue'
      fullPath: '/mgmt/revenue'
      preLoaderRoute: typeof AdministratorMgmtRevenueRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/invite-member': {
      id: '/_administrator/mgmt/invite-member'
      path: '/mgmt/invite-member'
      fullPath: '/mgmt/invite-member'
      preLoaderRoute: typeof AdministratorMgmtInviteMemberRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control': {
      id: '/_administrator/mgmt/access-control'
      path: '/mgmt/access-control'
      fullPath: '/mgmt/access-control'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/setting': {
      id: '/_administrator/financial/setting'
      path: '/financial/setting'
      fullPath: '/financial/setting'
      preLoaderRoute: typeof AdministratorFinancialSettingRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/receivables': {
      id: '/_administrator/financial/receivables'
      path: '/financial/receivables'
      fullPath: '/financial/receivables'
      preLoaderRoute: typeof AdministratorFinancialReceivablesRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/payment-channels': {
      id: '/_administrator/financial/payment-channels'
      path: '/financial/payment-channels'
      fullPath: '/financial/payment-channels'
      preLoaderRoute: typeof AdministratorFinancialPaymentChannelsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/ledger': {
      id: '/_administrator/financial/ledger'
      path: '/financial/ledger'
      fullPath: '/financial/ledger'
      preLoaderRoute: typeof AdministratorFinancialLedgerRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/financial/invoice-templates': {
      id: '/_administrator/financial/invoice-templates'
      path: '/financial/invoice-templates'
      fullPath: '/financial/invoice-templates'
      preLoaderRoute: typeof AdministratorFinancialInvoiceTemplatesRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/settings': {
      id: '/_administrator/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdministratorAdminSettingsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/schedule': {
      id: '/_administrator/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdministratorAdminScheduleRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/admin/inbox': {
      id: '/_administrator/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdministratorAdminInboxRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/staff-directory/': {
      id: '/_administrator/mgmt/staff-directory/'
      path: '/mgmt/staff-directory'
      fullPath: '/mgmt/staff-directory/'
      preLoaderRoute: typeof AdministratorMgmtStaffDirectoryIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/': {
      id: '/_administrator/mgmt/jobs/'
      path: '/mgmt/jobs'
      fullPath: '/mgmt/jobs/'
      preLoaderRoute: typeof AdministratorMgmtJobsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/file-docs/': {
      id: '/_administrator/mgmt/file-docs/'
      path: '/mgmt/file-docs'
      fullPath: '/mgmt/file-docs/'
      preLoaderRoute: typeof AdministratorMgmtFileDocsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/departments/': {
      id: '/_administrator/mgmt/departments/'
      path: '/mgmt/departments'
      fullPath: '/mgmt/departments/'
      preLoaderRoute: typeof AdministratorMgmtDepartmentsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/clients/': {
      id: '/_administrator/mgmt/clients/'
      path: '/mgmt/clients'
      fullPath: '/mgmt/clients/'
      preLoaderRoute: typeof AdministratorMgmtClientsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/': {
      id: '/_administrator/mgmt/access-control/'
      path: '/'
      fullPath: '/mgmt/access-control/'
      preLoaderRoute: typeof AdministratorMgmtAccessControlIndexRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/financial/payouts/': {
      id: '/_administrator/financial/payouts/'
      path: '/financial/payouts'
      fullPath: '/financial/payouts/'
      preLoaderRoute: typeof AdministratorFinancialPayoutsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/staff-directory/$code': {
      id: '/_administrator/mgmt/staff-directory/$code'
      path: '/mgmt/staff-directory/$code'
      fullPath: '/mgmt/staff-directory/$code'
      preLoaderRoute: typeof AdministratorMgmtStaffDirectoryCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/$no': {
      id: '/_administrator/mgmt/jobs/$no'
      path: '/mgmt/jobs/$no'
      fullPath: '/mgmt/jobs/$no'
      preLoaderRoute: typeof AdministratorMgmtJobsNoRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/departments/$code': {
      id: '/_administrator/mgmt/departments/$code'
      path: '/mgmt/departments/$code'
      fullPath: '/mgmt/departments/$code'
      preLoaderRoute: typeof AdministratorMgmtDepartmentsCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/clients/$code': {
      id: '/_administrator/mgmt/clients/$code'
      path: '/mgmt/clients/$code'
      fullPath: '/mgmt/clients/$code'
      preLoaderRoute: typeof AdministratorMgmtClientsCodeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/permissions': {
      id: '/_administrator/mgmt/access-control/permissions'
      path: '/permissions'
      fullPath: '/mgmt/access-control/permissions'
      preLoaderRoute: typeof AdministratorMgmtAccessControlPermissionsRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/mgmt/access-control/matrix': {
      id: '/_administrator/mgmt/access-control/matrix'
      path: '/matrix'
      fullPath: '/mgmt/access-control/matrix'
      preLoaderRoute: typeof AdministratorMgmtAccessControlMatrixRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/financial/payouts/$no': {
      id: '/_administrator/financial/payouts/$no'
      path: '/financial/payouts/$no'
      fullPath: '/financial/payouts/$no'
      preLoaderRoute: typeof AdministratorFinancialPayoutsNoRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/jobs/folder-templates/': {
      id: '/_administrator/mgmt/jobs/folder-templates/'
      path: '/mgmt/jobs/folder-templates'
      fullPath: '/mgmt/jobs/folder-templates/'
      preLoaderRoute: typeof AdministratorMgmtJobsFolderTemplatesIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/users/': {
      id: '/_administrator/mgmt/access-control/users/'
      path: '/users'
      fullPath: '/mgmt/access-control/users/'
      preLoaderRoute: typeof AdministratorMgmtAccessControlUsersIndexRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/mgmt/jobs/folder-templates/$id': {
      id: '/_administrator/mgmt/jobs/folder-templates/$id'
      path: '/mgmt/jobs/folder-templates/$id'
      fullPath: '/mgmt/jobs/folder-templates/$id'
      preLoaderRoute: typeof AdministratorMgmtJobsFolderTemplatesIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/_administrator/mgmt/access-control/users/$username': {
      id: '/_administrator/mgmt/access-control/users/$username'
      path: '/users/$username'
      fullPath: '/mgmt/access-control/users/$username'
      preLoaderRoute: typeof AdministratorMgmtAccessControlUsersUsernameRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/mgmt/access-control/roles/$code/': {
      id: '/_administrator/mgmt/access-control/roles/$code/'
      path: '/roles/$code'
      fullPath: '/mgmt/access-control/roles/$code/'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRolesCodeIndexRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
    '/_administrator/mgmt/access-control/roles/$code/perm-matrix': {
      id: '/_administrator/mgmt/access-control/roles/$code/perm-matrix'
      path: '/roles/$code/perm-matrix'
      fullPath: '/mgmt/access-control/roles/$code/perm-matrix'
      preLoaderRoute: typeof AdministratorMgmtAccessControlRolesCodePermMatrixRouteImport
      parentRoute: typeof AdministratorMgmtAccessControlRoute
    }
  }
}

interface AdministratorMgmtAccessControlRouteChildren {
  AdministratorMgmtAccessControlMatrixRoute: typeof AdministratorMgmtAccessControlMatrixRoute
  AdministratorMgmtAccessControlPermissionsRoute: typeof AdministratorMgmtAccessControlPermissionsRoute
  AdministratorMgmtAccessControlIndexRoute: typeof AdministratorMgmtAccessControlIndexRoute
  AdministratorMgmtAccessControlUsersUsernameRoute: typeof AdministratorMgmtAccessControlUsersUsernameRoute
  AdministratorMgmtAccessControlUsersIndexRoute: typeof AdministratorMgmtAccessControlUsersIndexRoute
  AdministratorMgmtAccessControlRolesCodePermMatrixRoute: typeof AdministratorMgmtAccessControlRolesCodePermMatrixRoute
  AdministratorMgmtAccessControlRolesCodeIndexRoute: typeof AdministratorMgmtAccessControlRolesCodeIndexRoute
}

const AdministratorMgmtAccessControlRouteChildren: AdministratorMgmtAccessControlRouteChildren =
  {
    AdministratorMgmtAccessControlMatrixRoute:
      AdministratorMgmtAccessControlMatrixRoute,
    AdministratorMgmtAccessControlPermissionsRoute:
      AdministratorMgmtAccessControlPermissionsRoute,
    AdministratorMgmtAccessControlIndexRoute:
      AdministratorMgmtAccessControlIndexRoute,
    AdministratorMgmtAccessControlUsersUsernameRoute:
      AdministratorMgmtAccessControlUsersUsernameRoute,
    AdministratorMgmtAccessControlUsersIndexRoute:
      AdministratorMgmtAccessControlUsersIndexRoute,
    AdministratorMgmtAccessControlRolesCodePermMatrixRoute:
      AdministratorMgmtAccessControlRolesCodePermMatrixRoute,
    AdministratorMgmtAccessControlRolesCodeIndexRoute:
      AdministratorMgmtAccessControlRolesCodeIndexRoute,
  }

const AdministratorMgmtAccessControlRouteWithChildren =
  AdministratorMgmtAccessControlRoute._addFileChildren(
    AdministratorMgmtAccessControlRouteChildren,
  )

interface AdministratorRouteChildren {
  AdministratorAdminInboxRoute: typeof AdministratorAdminInboxRoute
  AdministratorAdminScheduleRoute: typeof AdministratorAdminScheduleRoute
  AdministratorAdminSettingsRoute: typeof AdministratorAdminSettingsRoute
  AdministratorFinancialInvoiceTemplatesRoute: typeof AdministratorFinancialInvoiceTemplatesRoute
  AdministratorFinancialLedgerRoute: typeof AdministratorFinancialLedgerRoute
  AdministratorFinancialPaymentChannelsRoute: typeof AdministratorFinancialPaymentChannelsRoute
  AdministratorFinancialReceivablesRoute: typeof AdministratorFinancialReceivablesRoute
  AdministratorFinancialSettingRoute: typeof AdministratorFinancialSettingRoute
  AdministratorMgmtAccessControlRoute: typeof AdministratorMgmtAccessControlRouteWithChildren
  AdministratorMgmtInviteMemberRoute: typeof AdministratorMgmtInviteMemberRoute
  AdministratorMgmtRevenueRoute: typeof AdministratorMgmtRevenueRoute
  AdministratorAdminIndexRoute: typeof AdministratorAdminIndexRoute
  AdministratorFinancialIndexRoute: typeof AdministratorFinancialIndexRoute
  AdministratorFinancialPayoutsNoRoute: typeof AdministratorFinancialPayoutsNoRoute
  AdministratorMgmtClientsCodeRoute: typeof AdministratorMgmtClientsCodeRoute
  AdministratorMgmtDepartmentsCodeRoute: typeof AdministratorMgmtDepartmentsCodeRoute
  AdministratorMgmtJobsNoRoute: typeof AdministratorMgmtJobsNoRoute
  AdministratorMgmtStaffDirectoryCodeRoute: typeof AdministratorMgmtStaffDirectoryCodeRoute
  AdministratorFinancialPayoutsIndexRoute: typeof AdministratorFinancialPayoutsIndexRoute
  AdministratorMgmtClientsIndexRoute: typeof AdministratorMgmtClientsIndexRoute
  AdministratorMgmtDepartmentsIndexRoute: typeof AdministratorMgmtDepartmentsIndexRoute
  AdministratorMgmtFileDocsIndexRoute: typeof AdministratorMgmtFileDocsIndexRoute
  AdministratorMgmtJobsIndexRoute: typeof AdministratorMgmtJobsIndexRoute
  AdministratorMgmtStaffDirectoryIndexRoute: typeof AdministratorMgmtStaffDirectoryIndexRoute
  AdministratorMgmtJobsFolderTemplatesIdRoute: typeof AdministratorMgmtJobsFolderTemplatesIdRoute
  AdministratorMgmtJobsFolderTemplatesIndexRoute: typeof AdministratorMgmtJobsFolderTemplatesIndexRoute
}

const AdministratorRouteChildren: AdministratorRouteChildren = {
  AdministratorAdminInboxRoute: AdministratorAdminInboxRoute,
  AdministratorAdminScheduleRoute: AdministratorAdminScheduleRoute,
  AdministratorAdminSettingsRoute: AdministratorAdminSettingsRoute,
  AdministratorFinancialInvoiceTemplatesRoute:
    AdministratorFinancialInvoiceTemplatesRoute,
  AdministratorFinancialLedgerRoute: AdministratorFinancialLedgerRoute,
  AdministratorFinancialPaymentChannelsRoute:
    AdministratorFinancialPaymentChannelsRoute,
  AdministratorFinancialReceivablesRoute:
    AdministratorFinancialReceivablesRoute,
  AdministratorFinancialSettingRoute: AdministratorFinancialSettingRoute,
  AdministratorMgmtAccessControlRoute:
    AdministratorMgmtAccessControlRouteWithChildren,
  AdministratorMgmtInviteMemberRoute: AdministratorMgmtInviteMemberRoute,
  AdministratorMgmtRevenueRoute: AdministratorMgmtRevenueRoute,
  AdministratorAdminIndexRoute: AdministratorAdminIndexRoute,
  AdministratorFinancialIndexRoute: AdministratorFinancialIndexRoute,
  AdministratorFinancialPayoutsNoRoute: AdministratorFinancialPayoutsNoRoute,
  AdministratorMgmtClientsCodeRoute: AdministratorMgmtClientsCodeRoute,
  AdministratorMgmtDepartmentsCodeRoute: AdministratorMgmtDepartmentsCodeRoute,
  AdministratorMgmtJobsNoRoute: AdministratorMgmtJobsNoRoute,
  AdministratorMgmtStaffDirectoryCodeRoute:
    AdministratorMgmtStaffDirectoryCodeRoute,
  AdministratorFinancialPayoutsIndexRoute:
    AdministratorFinancialPayoutsIndexRoute,
  AdministratorMgmtClientsIndexRoute: AdministratorMgmtClientsIndexRoute,
  AdministratorMgmtDepartmentsIndexRoute:
    AdministratorMgmtDepartmentsIndexRoute,
  AdministratorMgmtFileDocsIndexRoute: AdministratorMgmtFileDocsIndexRoute,
  AdministratorMgmtJobsIndexRoute: AdministratorMgmtJobsIndexRoute,
  AdministratorMgmtStaffDirectoryIndexRoute:
    AdministratorMgmtStaffDirectoryIndexRoute,
  AdministratorMgmtJobsFolderTemplatesIdRoute:
    AdministratorMgmtJobsFolderTemplatesIdRoute,
  AdministratorMgmtJobsFolderTemplatesIndexRoute:
    AdministratorMgmtJobsFolderTemplatesIndexRoute,
}

const AdministratorRouteWithChildren = AdministratorRoute._addFileChildren(
  AdministratorRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicHelpCenterRoute: typeof PublicHelpCenterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHelpCenterRoute: PublicHelpCenterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface WorkspaceProjectCenterRouteChildren {
  WorkspaceProjectCenterTabRoute: typeof WorkspaceProjectCenterTabRoute
  WorkspaceProjectCenterIndexRoute: typeof WorkspaceProjectCenterIndexRoute
}

const WorkspaceProjectCenterRouteChildren: WorkspaceProjectCenterRouteChildren =
  {
    WorkspaceProjectCenterTabRoute: WorkspaceProjectCenterTabRoute,
    WorkspaceProjectCenterIndexRoute: WorkspaceProjectCenterIndexRoute,
  }

const WorkspaceProjectCenterRouteWithChildren =
  WorkspaceProjectCenterRoute._addFileChildren(
    WorkspaceProjectCenterRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceOverviewRoute: typeof WorkspaceOverviewRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceProjectCenterRoute: typeof WorkspaceProjectCenterRouteWithChildren
  WorkspaceScheduleRoute: typeof WorkspaceScheduleRoute
  WorkspaceTaskSummaryRoute: typeof WorkspaceTaskSummaryRoute
  WorkspaceJobsNoRoute: typeof WorkspaceJobsNoRoute
  WorkspaceWorkbenchIndexRoute: typeof WorkspaceWorkbenchIndexRoute
  WorkspaceJobsIndexRoute: typeof WorkspaceJobsIndexRoute
  WorkspaceNotificationsIndexRoute: typeof WorkspaceNotificationsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceOverviewRoute: WorkspaceOverviewRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceProjectCenterRoute: WorkspaceProjectCenterRouteWithChildren,
  WorkspaceScheduleRoute: WorkspaceScheduleRoute,
  WorkspaceTaskSummaryRoute: WorkspaceTaskSummaryRoute,
  WorkspaceJobsNoRoute: WorkspaceJobsNoRoute,
  WorkspaceWorkbenchIndexRoute: WorkspaceWorkbenchIndexRoute,
  WorkspaceJobsIndexRoute: WorkspaceJobsIndexRoute,
  WorkspaceNotificationsIndexRoute: WorkspaceNotificationsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLanguageAndRegionRoute: typeof SettingsLanguageAndRegionRoute
  SettingsLoginAndSecurityRoute: typeof SettingsLoginAndSecurityRoute
  SettingsMyProfileRoute: typeof SettingsMyProfileRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageAndRegionRoute: SettingsLanguageAndRegionRoute,
  SettingsLoginAndSecurityRoute: SettingsLoginAndSecurityRoute,
  SettingsMyProfileRoute: SettingsMyProfileRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdministratorRoute: AdministratorRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
