version: '3.8'
name: csd-staff

services:
  redis:
    container_name: cache
    image: redis:alpine3.22
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - '${DATA_PATH:-./.data}/redis:/data'
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-database}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cadsquaddb}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - '${DATA_PATH:-./.data}/postgres:/var/lib/postgresql/data'
      - ${LOG_PATH:-./logs}/postgres:/var/log/postgresql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-cadsquaddb}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-root}
    # Optional: To persist pgadmin configs/servers
    # PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - '${DATA_PATH:-./.data}/pgadmin:/var/lib/pgadmin'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:3
    container_name: ngrok
    restart: unless-stopped
    ports:
      - '4040:4040'
    depends_on:
      - backend
      - web_client
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    env_file: .env
    command: ['start', '--all', '--config', '/etc/ngrok.yml']
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    networks:
      - app-network

  prisma-studio:
    build:
      context: ./server
      target: deps
    container_name: prisma-studio
    command: bunx prisma studio --schema=./prisma/schema.prisma
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-cadsquaddb}?schema=public
    ports:
      - '5555:5555'
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ${LOG_PATH:-./logs}/backend:/app/logs # Giả sử ứng dụng ghi log vào /app/logs
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-cadsquaddb}?schema=public
      CLIENT_URL: ${CLIENT_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAILER_SECURE: ${MAILER_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      SMTP_URL: ${SMTP_URL:-smtp://${MAIL_USER}:${MAIL_PASS}@${MAIL_HOST}}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_AT: ${JWT_EXPIRES_AT}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER_ROOT: ${CLOUDINARY_FOLDER_ROOT}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ABLY_API_KEY: ${ABLY_API_KEY}
    networks:
      - app-network

  web_client:
    build:
      context: ./client
      dockerfile: Dockerfile # Ensure the Bun Dockerfile is in ./client
      args:
        VITE_APP_URL: ${CLIENT_URL:-http://web_client:80}
        VITE_API_ENDPOINT: '/api'
        # FIREBASE ARGS
        VITE_FIREBASE_VAPID_KEY: ${FIREBASE_VAPID_KEY}
        VITE_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
        VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
    container_name: web_client
    restart: always
    ports:
      - '80:80' # Map host 3000 to Nginx container 80
    depends_on:
      - backend
    env_file: .env
    volumes:
      - ${LOG_PATH:-./logs}/web_client:/var/log/nginx # Nếu dùng Nginx làm web server
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_APP_VERSION: ${CLIENT_VERSION:-0.0.0-release}
      VITE_APP_TITLE: ${APP_TITLE:-Cadsquad Staff}
      VITE_APP_URL: ${CLIENT_URL:-http://web_client:80}
      VITE_API_ENDPOINT: "/api"
      VITE_WS_URL: ${WS_URL}
      TAURI_DEV_HOST: ${TAURI_DEV_HOST}
      VITE_FIREBASE_VAPID_KEY: ${FIREBASE_VAPID_KEY}
      VITE_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
