// ============================================================================
// Types

import { INTERNAL_URLS } from '../utils'

// ============================================================================
export type TFAQ = {
    id: string
    question: string
    answer: string
    hasPermission?: string
}

export type TFAQGroup = {
    id: string
    title: string
    description: string
    faqIds: string[]
}

// ============================================================================
// Master Data Source
// ============================================================================

export const FAQS: TFAQ[] = [
    // Job Management (JOB)
    {
        id: 'JOB-001',
        question: 'How do I create a new job in the system?',
        answer: 'To create a new job, navigate to the <a href="/jobs/create">Job Creation page</a>. Fill in the required project details, client information, and deadlines. Once submitted, the job will be tracked in the system.',
        hasPermission: 'job.create',
    },
    {
        id: 'JOB-002',
        question: 'Can I edit the details of an existing job?',
        answer: `Yes, you can edit job details by selecting the specific job from the <a href="${INTERNAL_URLS.management.jobs}"}">Job List</a> and clicking the "Edit" button, or by visiting the edit page directly if you have the job no`,
        hasPermission: 'job.update',
    },
    {
        id: 'JOB-003',
        question: 'What is the procedure for deleting a job?',
        answer: 'If a job was created in error, it can be removed from the <a href="/jobs">Job Management</a> dashboard. Please note that this action is permanent and should be done with caution.',
        hasPermission: 'job.delete',
    },
    {
        id: 'JOB-004',
        question: 'How can I view all active and pending jobs?',
        answer: 'All jobs can be monitored through the comprehensive <a href="/jobs">Job Overview dashboard</a>, where you can filter by status, priority, and assigned staff.',
        hasPermission: 'job.readAll',
    },
    {
        id: 'JOB-005',
        question: 'Where can I track the income generated by a specific job?',
        answer: 'Financial performance and income tracking for jobs are available in the <a href="/jobs/financials">Financial Management</a> section. This view provides a detailed breakdown of revenue.',
        hasPermission: 'job.readIncome',
    },
    {
        id: 'JOB-006',
        question: 'How do I review the staff costs associated with a project?',
        answer: 'Staff cost analysis can be accessed via the <a href="/jobs/financials">Job Financials</a> page, helping you maintain project profitability and budget compliance.',
        hasPermission: 'job.readStaffCost',
    },
    {
        id: 'JOB-007',
        question: 'Is there a way to view jobs that have been cancelled?',
        answer: 'Yes, the system maintains a record of all projects. You can view them by selecting the "Cancelled" filter on the <a href="/jobs/cancelled">Job Archive</a> page.',
        hasPermission: 'job.readCancelled',
    },
    {
        id: 'JOB-008',
        question: 'How do I publish a job to make it visible to the team?',
        answer: 'Once a job draft is finalized, you can publish it using the "Publish" action on the <a href="/jobs">job details page</a>. This allows assigned members to begin their work.',
        hasPermission: 'job.publish',
    },
    {
        id: 'JOB-009',
        question: 'What is the process for marking a job as delivered?',
        answer: 'When the project outcomes are ready for the client, use the <a href="/jobs">Deliver Job</a> function. This changes the status and notifies relevant stakeholders.',
        hasPermission: 'job.deliver',
    },
    {
        id: 'JOB-010',
        question: 'How do I initiate a review for a completed job?',
        answer: 'Quality assurance reviews can be requested or performed through the <a href="/jobs">Job Review</a> interface, ensuring all deliverables meet CADSquad standards.',
        hasPermission: 'job.review',
    },
    {
        id: 'JOB-011',
        question: 'How are staff members assigned to a particular job?',
        answer: 'Resource allocation is managed through the <a href="/jobs/assignment">Staff Assignment</a> tool, where you can match team members with projects based on their expertise and availability.',
        hasPermission: 'job.assignment',
    },
    {
        id: 'JOB-012',
        question:
            'Can I update the financial estimates of a job after it has started?',
        answer: 'Financial adjustments can be made via the <a href="/jobs/financials">Financial Update</a> section of each job, allowing for real-time budget management.',
        hasPermission: 'job.updateFinancial',
    },
    {
        id: 'JOB-013',
        question: 'How do I record that a client has paid for a job?',
        answer: 'Payments are recorded by navigating to the specific <a href="/jobs">job details</a> and selecting "Record Payment" or "Mark as Paid" to update the financial status.',
        hasPermission: 'job.paid',
    },
    {
        id: 'JOB-014',
        question:
            'Where can I find the master management interface for all jobs?',
        answer: 'The primary control center for all operational tasks is the <a href="/jobs">Job Management Dashboard</a>, providing high-level oversight.',
        hasPermission: 'job.manage',
    },
    {
        id: 'JOB-015',
        question: 'Where do I define or modify the various job statuses?',
        answer: 'System-wide job statuses can be configured in the <a href="/settings/job-statuses">Job Status Settings</a>, allowing for custom workflow definitions.',
        hasPermission: 'jobStatus.manage',
    },
    {
        id: 'JOB-016',
        question: 'How do I add a new type of job to the system?',
        answer: 'New job categories and types can be created in the <a href="/settings/job-types">Job Type Configuration</a> area to better categorize your projects.',
        hasPermission: 'jobType.create',
    },
    {
        id: 'JOB-017',
        question: 'Can I modify the definitions of existing job types?',
        answer: 'Yes, job type metadata and settings can be updated through the <a href="/settings/job-types">Job Type Management</a> portal.',
        hasPermission: 'jobType.update',
    },
    {
        id: 'JOB-018',
        question: 'What if a job type is no longer needed?',
        answer: 'Unused or obsolete job types can be retired or deleted from the <a href="/settings/job-types">Job Type Settings</a> menu.',
        hasPermission: 'jobType.delete',
    },
    {
        id: 'JOB-019',
        question: 'How do I manage the overall workflow of job statuses?',
        answer: 'The lifecycle of a project is controlled through the <a href="/settings/job-statuses">Status Management</a> panel, where you can define transitions and triggers.',
        hasPermission: 'jobStatus.manage',
    },
    {
        id: 'JOB-020',
        question: 'How do I restrict who can change certain job statuses?',
        answer: 'Permission-based status transitions are configured in the <a href="/settings/job-statuses">Status Security Settings</a>, ensuring only authorized personnel can advance projects.',
        hasPermission: 'jobStatus.update',
    },
    {
        id: 'JOB-021',
        question: 'Is there a historical log for each job?',
        answer: 'The system maintains a full audit trail for every project. View the "Activity History" on any <a href="/jobs">job details page</a> to see all changes made.',
        hasPermission: 'job.readAll',
    },
    {
        id: 'JOB-022',
        question: 'How can I filter the job list by its current progress?',
        answer: 'Use the status filter dropdown on the <a href="/jobs">Job List page</a> to view only jobs that are "In Progress", "Reviewing", or "Completed".',
        hasPermission: 'job.readAll',
    },
    {
        id: 'JOB-023',
        question: 'Is there a search function for finding jobs by ID or Name?',
        answer: 'Yes, a global search bar is available at the top of the <a href="/jobs">Job Dashboard</a> for quick access to specific projects.',
        hasPermission: 'job.readAll',
    },
    {
        id: 'JOB-024',
        question: 'Can I export the current job list to a spreadsheet?',
        answer: 'Data export functionality is available on the <a href="/jobs/export">Job Export page</a>, supporting multiple formats for external reporting.',
        hasPermission: 'job.readAll',
    },
    {
        id: 'JOB-025',
        question: 'Where can I see the full technical details of a job?',
        answer: 'Clicking on any job entry in the <a href="/jobs">Job List</a> will take you to its detailed view, containing all specifications and linked documents.',
        hasPermission: 'job.readAll',
    },

    // User & Access Control (USER/ROLE)
    {
        id: 'USER-001',
        question: 'How do I onboard a new staff member into the system?',
        answer: 'New user accounts are created via the <a href="/admin/users/create">User Onboarding form</a>. You will need to provide their basic info and initial role assignment.',
        hasPermission: 'user.create',
    },
    {
        id: 'USER-002',
        question:
            "How can I update a user's personal or professional information?",
        answer: 'User profiles can be managed through the <a href="/admin/users">User Management</a> directory by selecting the "Edit" option on a user\'s profile.',
        hasPermission: 'user.update',
    },
    {
        id: 'USER-003',
        question: 'What is the procedure for removing a user account?',
        answer: 'To remove a user, navigate to the <a href="/admin/users">User List</a> and use the "Delete" action. Consider "Blocking" instead if you wish to preserve their historical data.',
        hasPermission: 'user.delete',
    },
    {
        id: 'USER-004',
        question: 'A user has forgotten their password. How can I help?',
        answer: 'Administrators can trigger a password reset from the <a href="/admin/users">User Details</a> page or via the <a href="/admin/users/reset-password">Reset Tool</a>.',
        hasPermission: 'user.resetPassword',
    },
    {
        id: 'USER-005',
        question: "How do I temporarily suspend a user's access?",
        answer: 'Use the "Block User" toggle on the <a href="/admin/users">User Management</a> page to immediately revoke all system access for a specific account.',
        hasPermission: 'user.block',
    },
    {
        id: 'USER-006',
        question: 'How are system roles and their permissions managed?',
        answer: 'Roles are defined and configured in the <a href="/admin/mgmt/roles">Role Management</a> section, where you can map permissions to specific job functions.',
        hasPermission: 'role.manage',
    },
    {
        id: 'USER-007',
        question: 'How do I grant specific permissions to a custom role?',
        answer: 'Permissions can be fine-tuned by editing a role in the <a href="/admin/mgmt/roles">Roles and Permissions</a> dashboard.',
        hasPermission: 'role.manage',
    },
    {
        id: 'USER-008',
        question: 'Where can I see an overview of all access control settings?',
        answer: 'The <a href="/admin/mgmt/access-control">Access Control Center</a> provides a holistic view of how users, roles, and permissions interact.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-009',
        question: 'How do I update my own profile information?',
        answer: 'You can manage your personal details, contact info, and preferences on the <a href="/settings/profile">My Profile</a> page.',
    },
    {
        id: 'USER-010',
        question: 'Where can I change my account password?',
        answer: 'Security settings, including password updates, are located in the <a href="/settings/profile/change-password">Security tab</a> of your profile.',
    },
    {
        id: 'USER-011',
        question: "How can I view a user's recent login and activity sessions?",
        answer: 'Detailed session logs and login history are available for each user in the <a href="/admin/users">User Sessions</a> report.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-012',
        question: 'How do I change the role assigned to a staff member?',
        answer: 'Navigate to <a href="/admin/users">User Management</a>, select the user, and update their role in the "Account Settings" section.',
        hasPermission: 'user.update',
    },
    {
        id: 'USER-013',
        question: 'What permissions are currently available in the system?',
        answer: 'A full list of system permissions and their descriptions can be found in the <a href="/admin/mgmt/access-control">Permission Reference</a>.',
        hasPermission: 'role.manage',
    },
    {
        id: 'USER-014',
        question: 'How do I move a user from one department to another?',
        answer: 'Departmental assignments are managed within the <a href="/admin/users">User Edit</a> interface under the "Organization" tab.',
        hasPermission: 'user.update',
    },
    {
        id: 'USER-015',
        question: 'Where is the master list of all registered users?',
        answer: 'The <a href="/admin/users">Staff Directory</a> serves as the central repository for all user accounts and their current status.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-016',
        question: 'Can I filter users based on their department?',
        answer: 'Yes, the <a href="/admin/users">User List</a> includes powerful filtering options, including department-based views.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-017',
        question: 'How do I search for a specific user by name or email?',
        answer: 'Use the global search tool on the <a href="/admin/users">User Management</a> dashboard to quickly locate any staff member.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-018',
        question: 'How do I manage active sessions for all users?',
        answer: 'Administrators can oversee and terminate active sessions system-wide from the <a href="/admin/users/sessions">Global Sessions</a> page.',
        hasPermission: 'user.manage',
    },
    {
        id: 'USER-019',
        question: "How do I update a staff member's formal job title?",
        answer: 'Job titles can be updated in the user profile settings via the <a href="/admin/users">User Management</a> portal.',
        hasPermission: 'user.update',
    },
    {
        id: 'USER-020',
        question: 'What should I do when an employee leaves the company?',
        answer: 'When a staff member departs, you should <a href="/admin/users">Block</a> their account to prevent access while maintaining their historical records.',
        hasPermission: 'user.block',
    },

    // Departments & Job Titles
    {
        id: 'DEPT-001',
        question: 'How do I register a new department in the system?',
        answer: 'New departments are defined in the <a href="/admin/departments/create">Department Setup</a> area, where you can specify names and managers.',
        hasPermission: 'department.create',
    },
    {
        id: 'DEPT-002',
        question:
            'How can I update the information for an existing department?',
        answer: 'Department details, including descriptions and hierarchy, can be edited in the <a href="/admin/departments">Department Management</a> section.',
        hasPermission: 'department.update',
    },
    {
        id: 'DEPT-003',
        question: 'What is the procedure for deleting an old department?',
        answer: 'Departments with no active users can be removed through the <a href="/admin/departments">Department List</a> interface.',
        hasPermission: 'department.delete',
    },
    {
        id: 'DEPT-004',
        question:
            'How do I access sensitive information regarding a department?',
        answer: 'Sensitive departmental data is restricted to authorized roles and can be viewed in the <a href="/admin/departments">Department Details</a> page.',
        hasPermission: 'department.readSensitive',
    },
    {
        id: 'DEPT-005',
        question:
            'Where can I find the management interface for all departments?',
        answer: 'The <a href="/admin/departments">Department Dashboard</a> is the central hub for organizing your company structure.',
        hasPermission: 'department.manage',
    },
    {
        id: 'DEPT-006',
        question: 'How do I create a new job title for our organization?',
        answer: 'Define new professional designations in the <a href="/admin/job-titles/create">Job Title Configuration</a> area.',
        hasPermission: 'jobTitle.create',
    },
    {
        id: 'DEPT-007',
        question: 'Can I edit the requirements or description of a job title?',
        answer: 'Yes, job title metadata can be managed through the <a href="/admin/job-titles">Job Title Management</a> portal.',
        hasPermission: 'jobTitle.update',
    },
    {
        id: 'DEPT-008',
        question: 'How do I remove a job title that is no longer in use?',
        answer: 'Obsolete job titles can be deleted from the <a href="/admin/job-titles">Job Title List</a>, provided they are not currently assigned to users.',
        hasPermission: 'jobTitle.delete',
    },
    {
        id: 'DEPT-009',
        question: 'Where is the master list of all job titles?',
        answer: 'The <a href="/admin/job-titles">Job Title Directory</a> provides a complete overview of all professional roles in the system.',
        hasPermission: 'jobTitle.manage',
    },
    {
        id: 'DEPT-010',
        question:
            'How can I view all staff members assigned to a specific department?',
        answer: 'The <a href="/admin/departments">Department Details</a> page provides a list of all members currently associated with that department.',
        hasPermission: 'department.manage',
    },

    // Clients & Payments
    {
        id: 'CLI-001',
        question: 'How do I add a new client to our database?',
        answer: 'Register new clients through the <a href="/clients/create">Client Registration form</a>, including contact info and billing details.',
        hasPermission: 'client.manage',
    },
    {
        id: 'CLI-002',
        question: "How can I update a client's contact or billing information?",
        answer: 'Client profiles can be updated by selecting the client from the <a href="/clients">Client Directory</a> and choosing "Edit".',
        hasPermission: 'client.write',
    },
    {
        id: 'CLI-003',
        question: "Where can I view a specific client's profile and history?",
        answer: 'Comprehensive client profiles, including all linked jobs and communications, are available in the <a href="/clients">Client Portfolio</a>.',
        hasPermission: 'client.read',
    },
    {
        id: 'CLI-004',
        question: 'What is the process for deleting a client record?',
        answer: 'Client records can be deactivated or removed via the <a href="/clients">Client Management</a> interface, though this is restricted to ensure data integrity.',
        hasPermission: 'client.manage',
    },
    {
        id: 'CLI-005',
        question: 'Where is the master management interface for all clients?',
        answer: 'The <a href="/clients">Client CRM Dashboard</a> is the primary tool for managing all external relationships.',
        hasPermission: 'client.manage',
    },
    {
        id: 'CLI-006',
        question: 'How do I set up a new payment channel (e.g., Bank, PayPal)?',
        answer: 'Payment methods are configured in the <a href="/admin/payments/channels/create">Payment Channel Settings</a>.',
        hasPermission: 'payment.create',
    },
    {
        id: 'CLI-007',
        question:
            'How can I modify the details of an existing payment channel?',
        answer: 'Existing payment configurations can be updated through the <a href="/admin/payments/channels">Payment Management</a> portal.',
        hasPermission: 'payment.update',
    },
    {
        id: 'CLI-008',
        question: 'How do I remove a payment channel that we no longer use?',
        answer: 'Unused payment channels can be deleted from the <a href="/admin/payments/channels">Channel List</a>.',
        hasPermission: 'payment.delete',
    },
    {
        id: 'CLI-009',
        question:
            'Where can I oversee all financial transactions and payments?',
        answer: 'The <a href="/admin/payments">Payment Operations Dashboard</a> provides oversight for all incoming and outgoing funds.',
        hasPermission: 'payment.manage',
    },
    {
        id: 'CLI-010',
        question:
            'How do I view all projects associated with a specific client?',
        answer: 'A full history of projects and jobs for any client is available on their respective <a href="/clients">Profile Page</a>.',
        hasPermission: 'client.read',
    },

    // File Management & Templates
    {
        id: 'FILE-001',
        question: 'How do I upload documents to a specific project?',
        answer: 'Files can be uploaded directly within any <a href="/jobs">Job Details page</a> or via the <a href="/files/upload">Global File Uploader</a>.',
        hasPermission: 'file.write',
    },
    {
        id: 'FILE-002',
        question: 'How can I download or view a stored file?',
        answer: 'Files can be accessed and downloaded from the <a href="/files">File Repository</a> or from the "Documents" tab of any job.',
        hasPermission: 'file.read',
    },
    {
        id: 'FILE-003',
        question: 'Where is the central repository for all system files?',
        answer: 'The <a href="/files">Master File Manager</a> allows you to browse, search, and organize all digital assets.',
        hasPermission: 'file.manage',
    },
    {
        id: 'FILE-004',
        question: 'What is the procedure for deleting a file?',
        answer: 'Files can be removed by authorized users within the <a href="/files">File Management</a> interface.',
        hasPermission: 'file.manage',
    },
    {
        id: 'FILE-005',
        question: 'How do I create a new folder structure template?',
        answer: 'Standardized folder structures for new jobs are created in the <a href="/settings/folder-templates/create">Folder Template Builder</a>.',
        hasPermission: 'folderTemplate.create',
    },
    {
        id: 'FILE-006',
        question: 'Can I edit the structure of an existing folder template?',
        answer: 'Yes, templates can be modified in the <a href="/settings/folder-templates">Template Management</a> section.',
        hasPermission: 'folderTemplate.update',
    },
    {
        id: 'FILE-007',
        question: 'How do I remove a folder template that is no longer needed?',
        answer: 'Folder templates can be deleted from the <a href="/settings/folder-templates">Template List</a>.',
        hasPermission: 'folderTemplate.delete',
    },
    {
        id: 'FILE-008',
        question: 'Where can I manage all system folder templates?',
        answer: 'The <a href="/settings/folder-templates">Template Dashboard</a> is where you organize all standard file structures.',
        hasPermission: 'folderTemplate.manage',
    },
    {
        id: 'FILE-009',
        question: 'How do I apply a folder template to a new or existing job?',
        answer: 'When viewing a <a href="/jobs">job details page</a>, you can select "Apply Template" to automatically generate the required folders.',
        hasPermission: 'job.update',
    },
    {
        id: 'FILE-010',
        question:
            'Is there a way to organize job-related files into categories?',
        answer: 'Yes, you can use the <a href="/jobs">File Management tab</a> within a job to create subfolders and categorize documents.',
        hasPermission: 'file.write',
    },

    // Analytics & Reports
    {
        id: 'ANA-001',
        question: 'Where can I view overall system performance analytics?',
        answer: 'The <a href="/analytics">Main Analytics Dashboard</a> provides high-level KPIs and performance metrics for the entire organization.',
        hasPermission: 'analytics.read',
    },
    {
        id: 'ANA-002',
        question: 'How do I generate a detailed financial report?',
        answer: 'Financial reports can be configured and generated in the <a href="/analytics/reports/financial">Reporting Center</a>.',
        hasPermission: 'analytics.report',
    },
    {
        id: 'ANA-003',
        question: 'How can I configure the parameters for automated reports?',
        answer: 'Reporting preferences and automated configurations are managed in the <a href="/analytics/settings">Analytics Configuration</a> area.',
        hasPermission: 'analytics.manage',
    },
    {
        id: 'ANA-004',
        question:
            'Where can I track staff productivity and performance metrics?',
        answer: 'Staff-specific analytics are available in the <a href="/analytics/staff">Human Resources Analytics</a> portal.',
        hasPermission: 'analytics.read',
    },
    {
        id: 'ANA-005',
        question:
            'How do I export analytics data for use in other applications?',
        answer: 'Data export tools are available on the <a href="/analytics/export">Analytics Export</a> page, supporting CSV and PDF formats.',
        hasPermission: 'analytics.report',
    },
    {
        id: 'ANA-006',
        question:
            'How can I track the progress of all jobs against their deadlines?',
        answer: 'Operational progress and deadline tracking are visualized in the <a href="/analytics/jobs">Project Analytics Dashboard</a>.',
        hasPermission: 'analytics.read',
    },
    {
        id: 'ANA-007',
        question:
            'Where can I find reports on client engagement and satisfaction?',
        answer: 'Client relationship metrics are located in the <a href="/analytics/clients">Client Insights</a> section of the analytics module.',
        hasPermission: 'analytics.report',
    },
    {
        id: 'ANA-008',
        question: 'Can I create a custom dashboard for my specific department?',
        answer: 'Custom dashboard configurations are managed through the <a href="/analytics/dashboards">Dashboard Management</a> tool.',
        hasPermission: 'analytics.manage',
    },
    {
        id: 'ANA-009',
        question: 'How do I monitor real-time activity across the system?',
        answer: 'The <a href="/analytics/activity">Real-Time Activity Stream</a> provides a live view of all system actions and updates.',
        hasPermission: 'analytics.read',
    },
    {
        id: 'ANA-010',
        question:
            'How do I schedule reports to be sent via email automatically?',
        answer: 'Report scheduling is handled in the <a href="/analytics/schedules">Report Scheduler</a>, allowing for daily, weekly, or monthly delivery.',
        hasPermission: 'analytics.manage',
    },

    // System Settings & Community
    {
        id: 'SYS-001',
        question:
            'Where are the core system settings and configurations located?',
        answer: 'Global system preferences and backend configurations are found in the <a href="/admin/settings">Main Settings Panel</a>.',
        hasPermission: 'system.manage',
    },
    {
        id: 'SYS-002',
        question: 'How do I create a new post for the company community?',
        answer: 'Share updates with the team by creating a new post on the <a href="/community/create">Community Page</a>.',
        hasPermission: 'post.create',
    },
    {
        id: 'SYS-003',
        question: 'How do I manage and moderate community posts?',
        answer: 'Post moderation and management tools are available in the <a href="/community/manage">Community Management Dashboard</a>.',
        hasPermission: 'post.manage',
    },
    {
        id: 'SYS-004',
        question: 'How do I create a new community group or forum?',
        answer: 'New community spaces can be established in the <a href="/community/groups/create">Group Creation</a> area.',
        hasPermission: 'community.create',
    },
    {
        id: 'SYS-005',
        question: 'Where can I manage existing community groups?',
        answer: 'The <a href="/community/groups/manage">Community Groups Manager</a> allows you to organize and edit various team spaces.',
        hasPermission: 'community.manage',
    },
    {
        id: 'SYS-006',
        question: 'How do I update the site title, logo, and branding?',
        answer: 'Branding and site-wide visual settings are managed in <a href="/admin/settings/site">Site Configuration</a>.',
        hasPermission: 'system.manage',
    },
    {
        id: 'SYS-007',
        question: 'Where can I edit the templates for system-generated emails?',
        answer: 'Email communication templates can be customized in the <a href="/admin/settings/emails">Email Template Manager</a>.',
        hasPermission: 'system.manage',
    },
    {
        id: 'SYS-008',
        question: 'How do I access and review the system audit logs?',
        answer: 'Detailed system activity and security logs are available in the <a href="/admin/settings/logs">Audit Log Viewer</a>.',
        hasPermission: 'system.manage',
    },
    {
        id: 'SYS-009',
        question: 'Where can I adjust my personal notification preferences?',
        answer: 'You can control which alerts you receive in the <a href="/settings/notifications">Notification Settings</a> section of your profile.',
    },
    {
        id: 'SYS-010',
        question: 'How do I update the rules and guidelines for our community?',
        answer: 'Community standards and rules can be edited in the <a href="/community/rules">Community Rules Configuration</a>.',
        hasPermission: 'community.manage',
    },
    {
        id: 'SYS-011',
        question: 'Is there a way to search through all community discussions?',
        answer: 'A comprehensive search tool for community content is available on the <a href="/community">Community Homepage</a>.',
        hasPermission: 'community.manage',
    },
    {
        id: 'SYS-012',
        question: 'How do I modify the settings of a specific community group?',
        answer: 'Select the group and navigate to its <a href="/community">Settings</a> page to update descriptions, privacy, and membership.',
        hasPermission: 'community.manage',
    },
    {
        id: 'SYS-013',
        question: 'What is the procedure for removing an inappropriate post?',
        answer: 'Authorized moderators can delete posts directly from the <a href="/community">Feed</a> or via the management portal.',
        hasPermission: 'post.manage',
    },
    {
        id: 'SYS-014',
        question: 'How do I configure integrations with third-party services?',
        answer: 'External API and service integrations are managed in the <a href="/admin/settings/integrations">Integrations Hub</a>.',
        hasPermission: 'system.manage',
    },
    {
        id: 'SYS-015',
        question:
            'Where can I check the current system version and release notes?',
        answer: 'Information about the current software version and recent updates is available in the <a href="/admin/settings/about">System Info</a> section.',
        hasPermission: 'system.manage',
    },
]

// ============================================================================
// Group Configuration
// ============================================================================

export const FAQ_GROUPS: TFAQGroup[] = [
    {
        id: 'settings',
        title: 'Settings',
        description: 'Account settings, appearance, and personal preferences.',
        faqIds: ['USER-009', 'USER-010', 'SYS-009'],
    },
    {
        id: 'system',
        title: 'System',
        description:
            'System overview, role management, and global configurations.',
        faqIds: [
            'USER-006',
            'USER-007',
            'USER-008',
            'USER-013',
            'SYS-001',
            'SYS-006',
            'SYS-007',
            'SYS-008',
            'SYS-014',
            'SYS-015',
        ],
    },
    {
        id: 'management-team',
        title: 'Team Management',
        description: 'Manage users, departments, and job titles.',
        faqIds: [
            'USER-001',
            'USER-002',
            'USER-003',
            'USER-004',
            'USER-005',
            'USER-011',
            'USER-012',
            'USER-014',
            'USER-015',
            'USER-016',
            'USER-017',
            'USER-018',
            'USER-019',
            'USER-020',
            'DEPT-001',
            'DEPT-002',
            'DEPT-003',
            'DEPT-004',
            'DEPT-005',
            'DEPT-006',
            'DEPT-007',
            'DEPT-008',
            'DEPT-009',
            'DEPT-010',
        ],
    },
    {
        id: 'management-jobs',
        title: 'Jobs Management',
        description: 'Job types, workflows, and operational status.',
        faqIds: [
            'JOB-001',
            'JOB-002',
            'JOB-003',
            'JOB-004',
            'JOB-007',
            'JOB-008',
            'JOB-009',
            'JOB-010',
            'JOB-011',
            'JOB-014',
            'JOB-015',
            'JOB-016',
            'JOB-017',
            'JOB-018',
            'JOB-019',
            'JOB-020',
            'JOB-021',
            'JOB-022',
            'JOB-023',
            'JOB-024',
            'JOB-025',
        ],
    },
    {
        id: 'management-templates',
        title: 'Folder Templates Management',
        description: 'Manage file structures and workspace templates.',
        faqIds: [
            'FILE-001',
            'FILE-002',
            'FILE-003',
            'FILE-004',
            'FILE-005',
            'FILE-006',
            'FILE-007',
            'FILE-008',
            'FILE-009',
            'FILE-010',
        ],
    },
    {
        id: 'management-clients',
        title: 'Clients Management',
        description: 'Manage corporate and individual clients.',
        faqIds: [
            'CLI-001',
            'CLI-002',
            'CLI-003',
            'CLI-004',
            'CLI-005',
            'CLI-010',
        ],
    },
    {
        id: 'management-payments',
        title: 'Payment Channels Management',
        description: 'Configure and manage payment methods.',
        faqIds: ['CLI-006', 'CLI-007', 'CLI-008', 'CLI-009'],
    },
    {
        id: 'financial',
        title: 'Financial Hub',
        description: 'Manage cash flow, staff payouts, and income.',
        faqIds: ['JOB-005', 'JOB-006', 'JOB-012', 'JOB-013'],
    },
    {
        id: 'analytics',
        title: 'Analytics & Reports',
        description: 'Business intelligence and performance metrics.',
        faqIds: [
            'ANA-001',
            'ANA-002',
            'ANA-003',
            'ANA-004',
            'ANA-005',
            'ANA-006',
            'ANA-007',
            'ANA-008',
            'ANA-009',
            'ANA-010',
        ],
    },
]
